package com.github.j5ik2o.reactive.aws.ecr.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToAuthorizationDataOps
    with ToBatchCheckLayerAvailabilityRequestOps
    with ToBatchCheckLayerAvailabilityResponseOps
    with ToBatchDeleteImageRequestOps
    with ToBatchDeleteImageResponseOps
    with ToBatchGetImageRequestOps
    with ToBatchGetImageResponseOps
    with ToCompleteLayerUploadRequestOps
    with ToCompleteLayerUploadResponseOps
    with ToCreateRepositoryRequestOps
    with ToCreateRepositoryResponseOps
    with ToDeleteLifecyclePolicyRequestOps
    with ToDeleteLifecyclePolicyResponseOps
    with ToDeleteRepositoryPolicyRequestOps
    with ToDeleteRepositoryPolicyResponseOps
    with ToDeleteRepositoryRequestOps
    with ToDeleteRepositoryResponseOps
    with ToDescribeImagesFilterOps
    with ToDescribeImagesRequestOps
    with ToDescribeImagesResponseOps
    with ToDescribeRepositoriesRequestOps
    with ToDescribeRepositoriesResponseOps
    with ToGetAuthorizationTokenRequestOps
    with ToGetAuthorizationTokenResponseOps
    with ToGetDownloadUrlForLayerRequestOps
    with ToGetDownloadUrlForLayerResponseOps
    with ToGetLifecyclePolicyPreviewRequestOps
    with ToGetLifecyclePolicyPreviewResponseOps
    with ToGetLifecyclePolicyRequestOps
    with ToGetLifecyclePolicyResponseOps
    with ToGetRepositoryPolicyRequestOps
    with ToGetRepositoryPolicyResponseOps
    with ToImageDetailOps
    with ToImageFailureOps
    with ToImageIdentifierOps
    with ToImageOps
    with ToInitiateLayerUploadRequestOps
    with ToInitiateLayerUploadResponseOps
    with ToLayerFailureOps
    with ToLayerOps
    with ToLifecyclePolicyPreviewFilterOps
    with ToLifecyclePolicyPreviewResultOps
    with ToLifecyclePolicyPreviewSummaryOps
    with ToLifecyclePolicyRuleActionOps
    with ToListImagesFilterOps
    with ToListImagesRequestOps
    with ToListImagesResponseOps
    with ToListTagsForResourceRequestOps
    with ToListTagsForResourceResponseOps
    with ToPutImageRequestOps
    with ToPutImageResponseOps
    with ToPutLifecyclePolicyRequestOps
    with ToPutLifecyclePolicyResponseOps
    with ToRepositoryOps
    with ToSetRepositoryPolicyRequestOps
    with ToSetRepositoryPolicyResponseOps
    with ToStartLifecyclePolicyPreviewRequestOps
    with ToStartLifecyclePolicyPreviewResponseOps
    with ToTagOps
    with ToTagResourceRequestOps
    with ToUntagResourceRequestOps
    with ToUploadLayerPartRequestOps
    with ToUploadLayerPartResponseOps
