package com.github.j5ik2o.reactive.aws.elasticsearch.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToAccessPoliciesStatusOps
    with ToAddTagsRequestOps
    with ToAdditionalLimitOps
    with ToAdvancedOptionsStatusOps
    with ToAdvancedSecurityOptionsInputOps
    with ToAdvancedSecurityOptionsOps
    with ToAdvancedSecurityOptionsStatusOps
    with ToAssociatePackageRequestOps
    with ToAssociatePackageResponseOps
    with ToCancelElasticsearchServiceSoftwareUpdateRequestOps
    with ToCancelElasticsearchServiceSoftwareUpdateResponseOps
    with ToCognitoOptionsOps
    with ToCognitoOptionsStatusOps
    with ToCompatibleVersionsMapOps
    with ToCreateElasticsearchDomainRequestOps
    with ToCreateElasticsearchDomainResponseOps
    with ToCreatePackageRequestOps
    with ToCreatePackageResponseOps
    with ToDeleteElasticsearchDomainRequestOps
    with ToDeleteElasticsearchDomainResponseOps
    with ToDeletePackageRequestOps
    with ToDeletePackageResponseOps
    with ToDescribeElasticsearchDomainConfigRequestOps
    with ToDescribeElasticsearchDomainConfigResponseOps
    with ToDescribeElasticsearchDomainRequestOps
    with ToDescribeElasticsearchDomainResponseOps
    with ToDescribeElasticsearchDomainsRequestOps
    with ToDescribeElasticsearchDomainsResponseOps
    with ToDescribeElasticsearchInstanceTypeLimitsRequestOps
    with ToDescribeElasticsearchInstanceTypeLimitsResponseOps
    with ToDescribePackagesFilterOps
    with ToDescribePackagesRequestOps
    with ToDescribePackagesResponseOps
    with ToDescribeReservedElasticsearchInstanceOfferingsRequestOps
    with ToDescribeReservedElasticsearchInstanceOfferingsResponseOps
    with ToDescribeReservedElasticsearchInstancesRequestOps
    with ToDescribeReservedElasticsearchInstancesResponseOps
    with ToDissociatePackageRequestOps
    with ToDissociatePackageResponseOps
    with ToDomainEndpointOptionsOps
    with ToDomainEndpointOptionsStatusOps
    with ToDomainInfoOps
    with ToDomainPackageDetailsOps
    with ToEBSOptionsOps
    with ToEBSOptionsStatusOps
    with ToElasticsearchClusterConfigOps
    with ToElasticsearchClusterConfigStatusOps
    with ToElasticsearchDomainConfigOps
    with ToElasticsearchDomainStatusOps
    with ToElasticsearchVersionStatusOps
    with ToEncryptionAtRestOptionsOps
    with ToEncryptionAtRestOptionsStatusOps
    with ToErrorDetailsOps
    with ToGetCompatibleElasticsearchVersionsRequestOps
    with ToGetCompatibleElasticsearchVersionsResponseOps
    with ToGetUpgradeHistoryRequestOps
    with ToGetUpgradeHistoryResponseOps
    with ToGetUpgradeStatusRequestOps
    with ToGetUpgradeStatusResponseOps
    with ToInstanceCountLimitsOps
    with ToInstanceLimitsOps
    with ToLimitsOps
    with ToListDomainNamesResponseOps
    with ToListDomainsForPackageRequestOps
    with ToListDomainsForPackageResponseOps
    with ToListElasticsearchInstanceTypesRequestOps
    with ToListElasticsearchInstanceTypesResponseOps
    with ToListElasticsearchVersionsRequestOps
    with ToListElasticsearchVersionsResponseOps
    with ToListPackagesForDomainRequestOps
    with ToListPackagesForDomainResponseOps
    with ToListTagsRequestOps
    with ToListTagsResponseOps
    with ToLogPublishingOptionOps
    with ToLogPublishingOptionsStatusOps
    with ToMasterUserOptionsOps
    with ToNodeToNodeEncryptionOptionsOps
    with ToNodeToNodeEncryptionOptionsStatusOps
    with ToOptionStatusOps
    with ToPackageDetailsOps
    with ToPackageSourceOps
    with ToPurchaseReservedElasticsearchInstanceOfferingRequestOps
    with ToPurchaseReservedElasticsearchInstanceOfferingResponseOps
    with ToRecurringChargeOps
    with ToRemoveTagsRequestOps
    with ToReservedElasticsearchInstanceOfferingOps
    with ToReservedElasticsearchInstanceOps
    with ToServiceSoftwareOptionsOps
    with ToSnapshotOptionsOps
    with ToSnapshotOptionsStatusOps
    with ToStartElasticsearchServiceSoftwareUpdateRequestOps
    with ToStartElasticsearchServiceSoftwareUpdateResponseOps
    with ToStorageTypeLimitOps
    with ToStorageTypeOps
    with ToTagOps
    with ToUpdateElasticsearchDomainConfigRequestOps
    with ToUpdateElasticsearchDomainConfigResponseOps
    with ToUpgradeElasticsearchDomainRequestOps
    with ToUpgradeElasticsearchDomainResponseOps
    with ToUpgradeHistoryOps
    with ToUpgradeStepItemOps
    with ToVPCDerivedInfoOps
    with ToVPCDerivedInfoStatusOps
    with ToVPCOptionsOps
    with ToZoneAwarenessConfigOps
