package com.github.j5ik2o.reactive.aws.appsync.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToApiKeyOps
    with ToAuthorizationConfigOps
    with ToAwsIamConfigOps
    with ToCreateApiKeyRequestOps
    with ToCreateApiKeyResponseOps
    with ToCreateDataSourceRequestOps
    with ToCreateDataSourceResponseOps
    with ToCreateFunctionRequestOps
    with ToCreateFunctionResponseOps
    with ToCreateGraphqlApiRequestOps
    with ToCreateGraphqlApiResponseOps
    with ToCreateResolverRequestOps
    with ToCreateResolverResponseOps
    with ToCreateTypeRequestOps
    with ToCreateTypeResponseOps
    with ToDataSourceOps
    with ToDeleteApiKeyRequestOps
    with ToDeleteApiKeyResponseOps
    with ToDeleteDataSourceRequestOps
    with ToDeleteDataSourceResponseOps
    with ToDeleteFunctionRequestOps
    with ToDeleteFunctionResponseOps
    with ToDeleteGraphqlApiRequestOps
    with ToDeleteGraphqlApiResponseOps
    with ToDeleteResolverRequestOps
    with ToDeleteResolverResponseOps
    with ToDeleteTypeRequestOps
    with ToDeleteTypeResponseOps
    with ToDynamodbDataSourceConfigOps
    with ToElasticsearchDataSourceConfigOps
    with ToFunctionConfigurationOps
    with ToGetDataSourceRequestOps
    with ToGetDataSourceResponseOps
    with ToGetFunctionRequestOps
    with ToGetFunctionResponseOps
    with ToGetGraphqlApiRequestOps
    with ToGetGraphqlApiResponseOps
    with ToGetIntrospectionSchemaRequestOps
    with ToGetIntrospectionSchemaResponseOps
    with ToGetResolverRequestOps
    with ToGetResolverResponseOps
    with ToGetSchemaCreationStatusRequestOps
    with ToGetSchemaCreationStatusResponseOps
    with ToGetTypeRequestOps
    with ToGetTypeResponseOps
    with ToGraphqlApiOps
    with ToHttpDataSourceConfigOps
    with ToLambdaDataSourceConfigOps
    with ToListApiKeysRequestOps
    with ToListApiKeysResponseOps
    with ToListDataSourcesRequestOps
    with ToListDataSourcesResponseOps
    with ToListFunctionsRequestOps
    with ToListFunctionsResponseOps
    with ToListGraphqlApisRequestOps
    with ToListGraphqlApisResponseOps
    with ToListResolversByFunctionRequestOps
    with ToListResolversByFunctionResponseOps
    with ToListResolversRequestOps
    with ToListResolversResponseOps
    with ToListTypesRequestOps
    with ToListTypesResponseOps
    with ToLogConfigOps
    with ToOpenIDConnectConfigOps
    with ToPipelineConfigOps
    with ToRdsHttpEndpointConfigOps
    with ToRelationalDatabaseDataSourceConfigOps
    with ToResolverOps
    with ToStartSchemaCreationRequestOps
    with ToStartSchemaCreationResponseOps
    with ToTypeOps
    with ToUpdateApiKeyRequestOps
    with ToUpdateApiKeyResponseOps
    with ToUpdateDataSourceRequestOps
    with ToUpdateDataSourceResponseOps
    with ToUpdateFunctionRequestOps
    with ToUpdateFunctionResponseOps
    with ToUpdateGraphqlApiRequestOps
    with ToUpdateGraphqlApiResponseOps
    with ToUpdateResolverRequestOps
    with ToUpdateResolverResponseOps
    with ToUpdateTypeRequestOps
    with ToUpdateTypeResponseOps
    with ToUserPoolConfigOps
