package com.github.j5ik2o.reactive.aws.elasticbeanstalk.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToAbortEnvironmentUpdateRequestOps
    with ToAbortEnvironmentUpdateResponseOps
    with ToApplicationDescriptionOps
    with ToApplicationMetricsOps
    with ToApplicationResourceLifecycleConfigOps
    with ToApplicationVersionDescriptionOps
    with ToApplicationVersionLifecycleConfigOps
    with ToApplyEnvironmentManagedActionRequestOps
    with ToApplyEnvironmentManagedActionResponseOps
    with ToAutoScalingGroupOps
    with ToBuildConfigurationOps
    with ToCPUUtilizationOps
    with ToCheckDnsAvailabilityRequestOps
    with ToCheckDnsAvailabilityResponseOps
    with ToComposeEnvironmentsRequestOps
    with ToComposeEnvironmentsResponseOps
    with ToConfigurationOptionDescriptionOps
    with ToConfigurationOptionSettingOps
    with ToConfigurationSettingsDescriptionOps
    with ToCreateApplicationRequestOps
    with ToCreateApplicationResponseOps
    with ToCreateApplicationVersionRequestOps
    with ToCreateApplicationVersionResponseOps
    with ToCreateConfigurationTemplateRequestOps
    with ToCreateConfigurationTemplateResponseOps
    with ToCreateEnvironmentRequestOps
    with ToCreateEnvironmentResponseOps
    with ToCreatePlatformVersionRequestOps
    with ToCreatePlatformVersionResponseOps
    with ToCreateStorageLocationRequestOps
    with ToCreateStorageLocationResponseOps
    with ToCustomAmiOps
    with ToDeleteApplicationRequestOps
    with ToDeleteApplicationResponseOps
    with ToDeleteApplicationVersionRequestOps
    with ToDeleteApplicationVersionResponseOps
    with ToDeleteConfigurationTemplateRequestOps
    with ToDeleteConfigurationTemplateResponseOps
    with ToDeleteEnvironmentConfigurationRequestOps
    with ToDeleteEnvironmentConfigurationResponseOps
    with ToDeletePlatformVersionRequestOps
    with ToDeletePlatformVersionResponseOps
    with ToDeploymentOps
    with ToDescribeAccountAttributesRequestOps
    with ToDescribeAccountAttributesResponseOps
    with ToDescribeApplicationVersionsRequestOps
    with ToDescribeApplicationVersionsResponseOps
    with ToDescribeApplicationsRequestOps
    with ToDescribeApplicationsResponseOps
    with ToDescribeConfigurationOptionsRequestOps
    with ToDescribeConfigurationOptionsResponseOps
    with ToDescribeConfigurationSettingsRequestOps
    with ToDescribeConfigurationSettingsResponseOps
    with ToDescribeEnvironmentHealthRequestOps
    with ToDescribeEnvironmentHealthResponseOps
    with ToDescribeEnvironmentManagedActionHistoryRequestOps
    with ToDescribeEnvironmentManagedActionHistoryResponseOps
    with ToDescribeEnvironmentManagedActionsRequestOps
    with ToDescribeEnvironmentManagedActionsResponseOps
    with ToDescribeEnvironmentResourcesRequestOps
    with ToDescribeEnvironmentResourcesResponseOps
    with ToDescribeEnvironmentsRequestOps
    with ToDescribeEnvironmentsResponseOps
    with ToDescribeEventsRequestOps
    with ToDescribeEventsResponseOps
    with ToDescribeInstancesHealthRequestOps
    with ToDescribeInstancesHealthResponseOps
    with ToDescribePlatformVersionRequestOps
    with ToDescribePlatformVersionResponseOps
    with ToEnvironmentDescriptionOps
    with ToEnvironmentInfoDescriptionOps
    with ToEnvironmentLinkOps
    with ToEnvironmentResourceDescriptionOps
    with ToEnvironmentResourcesDescriptionOps
    with ToEnvironmentTierOps
    with ToEventDescriptionOps
    with ToInstanceHealthSummaryOps
    with ToInstanceOps
    with ToLatencyOps
    with ToLaunchConfigurationOps
    with ToLaunchTemplateOps
    with ToListAvailableSolutionStacksRequestOps
    with ToListAvailableSolutionStacksResponseOps
    with ToListPlatformVersionsRequestOps
    with ToListPlatformVersionsResponseOps
    with ToListTagsForResourceRequestOps
    with ToListTagsForResourceResponseOps
    with ToListenerOps
    with ToLoadBalancerDescriptionOps
    with ToLoadBalancerOps
    with ToManagedActionHistoryItemOps
    with ToManagedActionOps
    with ToMaxAgeRuleOps
    with ToMaxCountRuleOps
    with ToOptionRestrictionRegexOps
    with ToOptionSpecificationOps
    with ToPlatformDescriptionOps
    with ToPlatformFilterOps
    with ToPlatformFrameworkOps
    with ToPlatformProgrammingLanguageOps
    with ToPlatformSummaryOps
    with ToQueueOps
    with ToRebuildEnvironmentRequestOps
    with ToRebuildEnvironmentResponseOps
    with ToRequestEnvironmentInfoRequestOps
    with ToRequestEnvironmentInfoResponseOps
    with ToResourceQuotaOps
    with ToResourceQuotasOps
    with ToRestartAppServerRequestOps
    with ToRestartAppServerResponseOps
    with ToRetrieveEnvironmentInfoRequestOps
    with ToRetrieveEnvironmentInfoResponseOps
    with ToS3LocationOps
    with ToSingleInstanceHealthOps
    with ToSolutionStackDescriptionOps
    with ToSourceBuildInformationOps
    with ToSourceConfigurationOps
    with ToStatusCodesOps
    with ToSwapEnvironmentCNAMEsResponseOps
    with ToSwapEnvironmentCnamEsRequestOps
    with ToSystemStatusOps
    with ToTagOps
    with ToTerminateEnvironmentRequestOps
    with ToTerminateEnvironmentResponseOps
    with ToTriggerOps
    with ToUpdateApplicationRequestOps
    with ToUpdateApplicationResourceLifecycleRequestOps
    with ToUpdateApplicationResourceLifecycleResponseOps
    with ToUpdateApplicationResponseOps
    with ToUpdateApplicationVersionRequestOps
    with ToUpdateApplicationVersionResponseOps
    with ToUpdateConfigurationTemplateRequestOps
    with ToUpdateConfigurationTemplateResponseOps
    with ToUpdateEnvironmentRequestOps
    with ToUpdateEnvironmentResponseOps
    with ToUpdateTagsForResourceRequestOps
    with ToUpdateTagsForResourceResponseOps
    with ToValidateConfigurationSettingsRequestOps
    with ToValidateConfigurationSettingsResponseOps
    with ToValidationMessageOps
