package com.github.j5ik2o.reactive.aws.dynamodb.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToAttributeDefinitionOps
    with ToAttributeValueOps
    with ToAttributeValueUpdateOps
    with ToAutoScalingPolicyDescriptionOps
    with ToAutoScalingPolicyUpdateOps
    with ToAutoScalingSettingsDescriptionOps
    with ToAutoScalingSettingsUpdateOps
    with ToAutoScalingTargetTrackingScalingPolicyConfigurationDescriptionOps
    with ToAutoScalingTargetTrackingScalingPolicyConfigurationUpdateOps
    with ToBackupDescriptionOps
    with ToBackupDetailsOps
    with ToBackupSummaryOps
    with ToBatchGetItemRequestOps
    with ToBatchGetItemResponseOps
    with ToBatchWriteItemRequestOps
    with ToBatchWriteItemResponseOps
    with ToBillingModeSummaryOps
    with ToCancellationReasonOps
    with ToCapacityOps
    with ToConditionCheckOps
    with ToConditionOps
    with ToConsumedCapacityOps
    with ToContinuousBackupsDescriptionOps
    with ToCreateBackupRequestOps
    with ToCreateBackupResponseOps
    with ToCreateGlobalSecondaryIndexActionOps
    with ToCreateGlobalTableRequestOps
    with ToCreateGlobalTableResponseOps
    with ToCreateReplicaActionOps
    with ToCreateTableRequestOps
    with ToCreateTableResponseOps
    with ToDeleteBackupRequestOps
    with ToDeleteBackupResponseOps
    with ToDeleteGlobalSecondaryIndexActionOps
    with ToDeleteItemRequestOps
    with ToDeleteItemResponseOps
    with ToDeleteOps
    with ToDeleteReplicaActionOps
    with ToDeleteRequestOps
    with ToDeleteTableRequestOps
    with ToDeleteTableResponseOps
    with ToDescribeBackupRequestOps
    with ToDescribeBackupResponseOps
    with ToDescribeContinuousBackupsRequestOps
    with ToDescribeContinuousBackupsResponseOps
    with ToDescribeEndpointsRequestOps
    with ToDescribeEndpointsResponseOps
    with ToDescribeGlobalTableRequestOps
    with ToDescribeGlobalTableResponseOps
    with ToDescribeGlobalTableSettingsRequestOps
    with ToDescribeGlobalTableSettingsResponseOps
    with ToDescribeLimitsRequestOps
    with ToDescribeLimitsResponseOps
    with ToDescribeStreamRequestOps
    with ToDescribeStreamResponseOps
    with ToDescribeTableRequestOps
    with ToDescribeTableResponseOps
    with ToDescribeTimeToLiveRequestOps
    with ToDescribeTimeToLiveResponseOps
    with ToEndpointOps
    with ToExpectedAttributeValueOps
    with ToGetItemRequestOps
    with ToGetItemResponseOps
    with ToGetOps
    with ToGetRecordsRequestOps
    with ToGetRecordsResponseOps
    with ToGetShardIteratorRequestOps
    with ToGetShardIteratorResponseOps
    with ToGlobalSecondaryIndexDescriptionOps
    with ToGlobalSecondaryIndexInfoOps
    with ToGlobalSecondaryIndexOps
    with ToGlobalSecondaryIndexUpdateOps
    with ToGlobalTableDescriptionOps
    with ToGlobalTableGlobalSecondaryIndexSettingsUpdateOps
    with ToGlobalTableOps
    with ToIdentityOps
    with ToItemCollectionMetricsOps
    with ToItemResponseOps
    with ToKeySchemaElementOps
    with ToKeysAndAttributesOps
    with ToListBackupsRequestOps
    with ToListBackupsResponseOps
    with ToListGlobalTablesRequestOps
    with ToListGlobalTablesResponseOps
    with ToListStreamsRequestOps
    with ToListStreamsResponseOps
    with ToListTablesRequestOps
    with ToListTablesResponseOps
    with ToListTagsOfResourceRequestOps
    with ToListTagsOfResourceResponseOps
    with ToLocalSecondaryIndexDescriptionOps
    with ToLocalSecondaryIndexInfoOps
    with ToLocalSecondaryIndexOps
    with ToPointInTimeRecoveryDescriptionOps
    with ToPointInTimeRecoverySpecificationOps
    with ToProjectionOps
    with ToProvisionedThroughputDescriptionOps
    with ToProvisionedThroughputOps
    with ToPutItemRequestOps
    with ToPutItemResponseOps
    with ToPutOps
    with ToPutRequestOps
    with ToQueryRequestOps
    with ToQueryResponseOps
    with ToRecordOps
    with ToReplicaDescriptionOps
    with ToReplicaGlobalSecondaryIndexSettingsDescriptionOps
    with ToReplicaGlobalSecondaryIndexSettingsUpdateOps
    with ToReplicaOps
    with ToReplicaSettingsDescriptionOps
    with ToReplicaSettingsUpdateOps
    with ToReplicaUpdateOps
    with ToRestoreSummaryOps
    with ToRestoreTableFromBackupRequestOps
    with ToRestoreTableFromBackupResponseOps
    with ToRestoreTableToPointInTimeRequestOps
    with ToRestoreTableToPointInTimeResponseOps
    with ToSSEDescriptionOps
    with ToSSESpecificationOps
    with ToScanRequestOps
    with ToScanResponseOps
    with ToSequenceNumberRangeOps
    with ToShardOps
    with ToSourceTableDetailsOps
    with ToSourceTableFeatureDetailsOps
    with ToStreamDescriptionOps
    with ToStreamOps
    with ToStreamRecordOps
    with ToStreamSpecificationOps
    with ToTableDescriptionOps
    with ToTagOps
    with ToTagResourceRequestOps
    with ToTagResourceResponseOps
    with ToTimeToLiveDescriptionOps
    with ToTimeToLiveSpecificationOps
    with ToTransactGetItemOps
    with ToTransactGetItemsRequestOps
    with ToTransactGetItemsResponseOps
    with ToTransactWriteItemOps
    with ToTransactWriteItemsRequestOps
    with ToTransactWriteItemsResponseOps
    with ToUntagResourceRequestOps
    with ToUntagResourceResponseOps
    with ToUpdateContinuousBackupsRequestOps
    with ToUpdateContinuousBackupsResponseOps
    with ToUpdateGlobalSecondaryIndexActionOps
    with ToUpdateGlobalTableRequestOps
    with ToUpdateGlobalTableResponseOps
    with ToUpdateGlobalTableSettingsRequestOps
    with ToUpdateGlobalTableSettingsResponseOps
    with ToUpdateItemRequestOps
    with ToUpdateItemResponseOps
    with ToUpdateOps
    with ToUpdateTableRequestOps
    with ToUpdateTableResponseOps
    with ToUpdateTimeToLiveRequestOps
    with ToUpdateTimeToLiveResponseOps
    with ToWriteRequestOps
