package com.github.j5ik2o.reactive.aws.lambda.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToAccountLimitOps
    with ToAccountUsageOps
    with ToAddLayerVersionPermissionRequestOps
    with ToAddLayerVersionPermissionResponseOps
    with ToAddPermissionRequestOps
    with ToAddPermissionResponseOps
    with ToAliasConfigurationOps
    with ToAliasRoutingConfigurationOps
    with ToConcurrencyOps
    with ToCreateAliasRequestOps
    with ToCreateAliasResponseOps
    with ToCreateEventSourceMappingRequestOps
    with ToCreateEventSourceMappingResponseOps
    with ToCreateFunctionRequestOps
    with ToCreateFunctionResponseOps
    with ToDeadLetterConfigOps
    with ToDeleteAliasRequestOps
    with ToDeleteEventSourceMappingRequestOps
    with ToDeleteEventSourceMappingResponseOps
    with ToDeleteFunctionConcurrencyRequestOps
    with ToDeleteFunctionRequestOps
    with ToDeleteLayerVersionRequestOps
    with ToEnvironmentErrorOps
    with ToEnvironmentOps
    with ToEnvironmentResponseOps
    with ToEventSourceMappingConfigurationOps
    with ToFunctionCodeLocationOps
    with ToFunctionCodeOps
    with ToFunctionConfigurationOps
    with ToGetAccountSettingsResponseOps
    with ToGetAliasRequestOps
    with ToGetAliasResponseOps
    with ToGetEventSourceMappingRequestOps
    with ToGetEventSourceMappingResponseOps
    with ToGetFunctionConfigurationRequestOps
    with ToGetFunctionConfigurationResponseOps
    with ToGetFunctionRequestOps
    with ToGetFunctionResponseOps
    with ToGetLayerVersionPolicyRequestOps
    with ToGetLayerVersionPolicyResponseOps
    with ToGetLayerVersionRequestOps
    with ToGetLayerVersionResponseOps
    with ToGetPolicyRequestOps
    with ToGetPolicyResponseOps
    with ToInvokeRequestOps
    with ToInvokeResponseOps
    with ToLayerOps
    with ToLayerVersionContentInputOps
    with ToLayerVersionContentOutputOps
    with ToLayerVersionsListItemOps
    with ToLayersListItemOps
    with ToListAliasesRequestOps
    with ToListAliasesResponseOps
    with ToListEventSourceMappingsRequestOps
    with ToListEventSourceMappingsResponseOps
    with ToListFunctionsRequestOps
    with ToListFunctionsResponseOps
    with ToListLayerVersionsRequestOps
    with ToListLayerVersionsResponseOps
    with ToListLayersRequestOps
    with ToListLayersResponseOps
    with ToListTagsRequestOps
    with ToListTagsResponseOps
    with ToListVersionsByFunctionRequestOps
    with ToListVersionsByFunctionResponseOps
    with ToPublishLayerVersionRequestOps
    with ToPublishLayerVersionResponseOps
    with ToPublishVersionRequestOps
    with ToPublishVersionResponseOps
    with ToPutFunctionConcurrencyRequestOps
    with ToPutFunctionConcurrencyResponseOps
    with ToRemoveLayerVersionPermissionRequestOps
    with ToRemovePermissionRequestOps
    with ToTagResourceRequestOps
    with ToTracingConfigOps
    with ToTracingConfigResponseOps
    with ToUntagResourceRequestOps
    with ToUpdateAliasRequestOps
    with ToUpdateAliasResponseOps
    with ToUpdateEventSourceMappingRequestOps
    with ToUpdateEventSourceMappingResponseOps
    with ToUpdateFunctionCodeRequestOps
    with ToUpdateFunctionCodeResponseOps
    with ToUpdateFunctionConfigurationRequestOps
    with ToUpdateFunctionConfigurationResponseOps
    with ToVpcConfigOps
    with ToVpcConfigResponseOps
