package com.github.j5ik2o.reactive.aws.dax.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToClusterOps
    with ToCreateClusterRequestOps
    with ToCreateClusterResponseOps
    with ToCreateParameterGroupRequestOps
    with ToCreateParameterGroupResponseOps
    with ToCreateSubnetGroupRequestOps
    with ToCreateSubnetGroupResponseOps
    with ToDecreaseReplicationFactorRequestOps
    with ToDecreaseReplicationFactorResponseOps
    with ToDeleteClusterRequestOps
    with ToDeleteClusterResponseOps
    with ToDeleteParameterGroupRequestOps
    with ToDeleteParameterGroupResponseOps
    with ToDeleteSubnetGroupRequestOps
    with ToDeleteSubnetGroupResponseOps
    with ToDescribeClustersRequestOps
    with ToDescribeClustersResponseOps
    with ToDescribeDefaultParametersRequestOps
    with ToDescribeDefaultParametersResponseOps
    with ToDescribeEventsRequestOps
    with ToDescribeEventsResponseOps
    with ToDescribeParameterGroupsRequestOps
    with ToDescribeParameterGroupsResponseOps
    with ToDescribeParametersRequestOps
    with ToDescribeParametersResponseOps
    with ToDescribeSubnetGroupsRequestOps
    with ToDescribeSubnetGroupsResponseOps
    with ToEndpointOps
    with ToEventOps
    with ToIncreaseReplicationFactorRequestOps
    with ToIncreaseReplicationFactorResponseOps
    with ToListTagsRequestOps
    with ToListTagsResponseOps
    with ToNodeOps
    with ToNodeTypeSpecificValueOps
    with ToNotificationConfigurationOps
    with ToParameterGroupOps
    with ToParameterGroupStatusOps
    with ToParameterNameValueOps
    with ToParameterOps
    with ToRebootNodeRequestOps
    with ToRebootNodeResponseOps
    with ToSSEDescriptionOps
    with ToSSESpecificationOps
    with ToSecurityGroupMembershipOps
    with ToSubnetGroupOps
    with ToSubnetOps
    with ToTagOps
    with ToTagResourceRequestOps
    with ToTagResourceResponseOps
    with ToUntagResourceRequestOps
    with ToUntagResourceResponseOps
    with ToUpdateClusterRequestOps
    with ToUpdateClusterResponseOps
    with ToUpdateParameterGroupRequestOps
    with ToUpdateParameterGroupResponseOps
    with ToUpdateSubnetGroupRequestOps
    with ToUpdateSubnetGroupResponseOps
