package com.github.j5ik2o.reactive.aws.sqs.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToAddPermissionRequestOps
    with ToAddPermissionResponseOps
    with ToBatchResultErrorEntryOps
    with ToChangeMessageVisibilityBatchRequestEntryOps
    with ToChangeMessageVisibilityBatchRequestOps
    with ToChangeMessageVisibilityBatchResponseOps
    with ToChangeMessageVisibilityBatchResultEntryOps
    with ToChangeMessageVisibilityRequestOps
    with ToChangeMessageVisibilityResponseOps
    with ToCreateQueueRequestOps
    with ToCreateQueueResponseOps
    with ToDeleteMessageBatchRequestEntryOps
    with ToDeleteMessageBatchRequestOps
    with ToDeleteMessageBatchResponseOps
    with ToDeleteMessageBatchResultEntryOps
    with ToDeleteMessageRequestOps
    with ToDeleteMessageResponseOps
    with ToDeleteQueueRequestOps
    with ToDeleteQueueResponseOps
    with ToGetQueueAttributesRequestOps
    with ToGetQueueAttributesResponseOps
    with ToGetQueueUrlRequestOps
    with ToGetQueueUrlResponseOps
    with ToListDeadLetterSourceQueuesRequestOps
    with ToListDeadLetterSourceQueuesResponseOps
    with ToListQueueTagsRequestOps
    with ToListQueueTagsResponseOps
    with ToListQueuesRequestOps
    with ToListQueuesResponseOps
    with ToMessageAttributeValueOps
    with ToMessageOps
    with ToPurgeQueueRequestOps
    with ToPurgeQueueResponseOps
    with ToReceiveMessageRequestOps
    with ToReceiveMessageResponseOps
    with ToRemovePermissionRequestOps
    with ToRemovePermissionResponseOps
    with ToSendMessageBatchRequestEntryOps
    with ToSendMessageBatchRequestOps
    with ToSendMessageBatchResponseOps
    with ToSendMessageBatchResultEntryOps
    with ToSendMessageRequestOps
    with ToSendMessageResponseOps
    with ToSetQueueAttributesRequestOps
    with ToSetQueueAttributesResponseOps
    with ToTagQueueRequestOps
    with ToTagQueueResponseOps
    with ToUntagQueueRequestOps
    with ToUntagQueueResponseOps
