package com.github.j5ik2o.reactive.aws.rekognition.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToAgeRangeOps
    with ToAssetOps
    with ToBeardOps
    with ToBoundingBoxOps
    with ToCelebrityDetailOps
    with ToCelebrityOps
    with ToCelebrityRecognitionOps
    with ToCompareFacesMatchOps
    with ToCompareFacesRequestOps
    with ToCompareFacesResponseOps
    with ToComparedFaceOps
    with ToComparedSourceImageFaceOps
    with ToContentModerationDetectionOps
    with ToCreateCollectionRequestOps
    with ToCreateCollectionResponseOps
    with ToCreateProjectRequestOps
    with ToCreateProjectResponseOps
    with ToCreateProjectVersionRequestOps
    with ToCreateProjectVersionResponseOps
    with ToCreateStreamProcessorRequestOps
    with ToCreateStreamProcessorResponseOps
    with ToCustomLabelOps
    with ToDeleteCollectionRequestOps
    with ToDeleteCollectionResponseOps
    with ToDeleteFacesRequestOps
    with ToDeleteFacesResponseOps
    with ToDeleteStreamProcessorRequestOps
    with ToDescribeCollectionRequestOps
    with ToDescribeCollectionResponseOps
    with ToDescribeProjectVersionsRequestOps
    with ToDescribeProjectVersionsResponseOps
    with ToDescribeProjectsRequestOps
    with ToDescribeProjectsResponseOps
    with ToDescribeStreamProcessorRequestOps
    with ToDescribeStreamProcessorResponseOps
    with ToDetectCustomLabelsRequestOps
    with ToDetectCustomLabelsResponseOps
    with ToDetectFacesRequestOps
    with ToDetectFacesResponseOps
    with ToDetectLabelsRequestOps
    with ToDetectLabelsResponseOps
    with ToDetectModerationLabelsRequestOps
    with ToDetectModerationLabelsResponseOps
    with ToDetectTextFiltersOps
    with ToDetectTextRequestOps
    with ToDetectTextResponseOps
    with ToDetectionFilterOps
    with ToEmotionOps
    with ToEvaluationResultOps
    with ToEyeOpenOps
    with ToEyeglassesOps
    with ToFaceDetailOps
    with ToFaceDetectionOps
    with ToFaceMatchOps
    with ToFaceOps
    with ToFaceRecordOps
    with ToFaceSearchSettingsOps
    with ToGenderOps
    with ToGeometryOps
    with ToGetCelebrityInfoRequestOps
    with ToGetCelebrityInfoResponseOps
    with ToGetCelebrityRecognitionRequestOps
    with ToGetCelebrityRecognitionResponseOps
    with ToGetContentModerationRequestOps
    with ToGetContentModerationResponseOps
    with ToGetFaceDetectionRequestOps
    with ToGetFaceDetectionResponseOps
    with ToGetFaceSearchRequestOps
    with ToGetFaceSearchResponseOps
    with ToGetLabelDetectionRequestOps
    with ToGetLabelDetectionResponseOps
    with ToGetPersonTrackingRequestOps
    with ToGetPersonTrackingResponseOps
    with ToGetTextDetectionRequestOps
    with ToGetTextDetectionResponseOps
    with ToGroundTruthManifestOps
    with ToHumanLoopActivationOutputOps
    with ToHumanLoopConfigOps
    with ToHumanLoopDataAttributesOps
    with ToImageOps
    with ToImageQualityOps
    with ToIndexFacesRequestOps
    with ToIndexFacesResponseOps
    with ToInstanceOps
    with ToKinesisDataStreamOps
    with ToKinesisVideoStreamOps
    with ToLabelDetectionOps
    with ToLabelOps
    with ToLandmarkOps
    with ToListCollectionsRequestOps
    with ToListCollectionsResponseOps
    with ToListFacesRequestOps
    with ToListFacesResponseOps
    with ToListStreamProcessorsRequestOps
    with ToListStreamProcessorsResponseOps
    with ToModerationLabelOps
    with ToMouthOpenOps
    with ToMustacheOps
    with ToNotificationChannelOps
    with ToOutputConfigOps
    with ToParentOps
    with ToPersonDetailOps
    with ToPersonDetectionOps
    with ToPersonMatchOps
    with ToPointOps
    with ToPoseOps
    with ToProjectDescriptionOps
    with ToProjectVersionDescriptionOps
    with ToRecognizeCelebritiesRequestOps
    with ToRecognizeCelebritiesResponseOps
    with ToRegionOfInterestOps
    with ToS3ObjectOps
    with ToSearchFacesByImageRequestOps
    with ToSearchFacesByImageResponseOps
    with ToSearchFacesRequestOps
    with ToSearchFacesResponseOps
    with ToSmileOps
    with ToStartCelebrityRecognitionRequestOps
    with ToStartCelebrityRecognitionResponseOps
    with ToStartContentModerationRequestOps
    with ToStartContentModerationResponseOps
    with ToStartFaceDetectionRequestOps
    with ToStartFaceDetectionResponseOps
    with ToStartFaceSearchRequestOps
    with ToStartFaceSearchResponseOps
    with ToStartLabelDetectionRequestOps
    with ToStartLabelDetectionResponseOps
    with ToStartPersonTrackingRequestOps
    with ToStartPersonTrackingResponseOps
    with ToStartProjectVersionRequestOps
    with ToStartProjectVersionResponseOps
    with ToStartStreamProcessorRequestOps
    with ToStartTextDetectionFiltersOps
    with ToStartTextDetectionRequestOps
    with ToStartTextDetectionResponseOps
    with ToStopProjectVersionRequestOps
    with ToStopProjectVersionResponseOps
    with ToStopStreamProcessorRequestOps
    with ToStreamProcessorInputOps
    with ToStreamProcessorOps
    with ToStreamProcessorOutputOps
    with ToStreamProcessorSettingsOps
    with ToSummaryOps
    with ToSunglassesOps
    with ToTestingDataOps
    with ToTestingDataResultOps
    with ToTextDetectionOps
    with ToTextDetectionResultOps
    with ToTrainingDataOps
    with ToTrainingDataResultOps
    with ToUnindexedFaceOps
    with ToVideoMetadataOps
    with ToVideoOps
