package com.github.j5ik2o.reactive.aws.rekognition.model.ops

trait ToAllOps
    extends ToAgeRangeOps
    with ToBeardOps
    with ToBoundingBoxOps
    with ToCelebrityDetailOps
    with ToCelebrityOps
    with ToCelebrityRecognitionOps
    with ToCompareFacesMatchOps
    with ToCompareFacesRequestOps
    with ToCompareFacesResponseOps
    with ToComparedFaceOps
    with ToComparedSourceImageFaceOps
    with ToContentModerationDetectionOps
    with ToCreateCollectionRequestOps
    with ToCreateCollectionResponseOps
    with ToCreateStreamProcessorRequestOps
    with ToCreateStreamProcessorResponseOps
    with ToDeleteCollectionRequestOps
    with ToDeleteCollectionResponseOps
    with ToDeleteFacesRequestOps
    with ToDeleteFacesResponseOps
    with ToDeleteStreamProcessorRequestOps
    with ToDescribeCollectionRequestOps
    with ToDescribeCollectionResponseOps
    with ToDescribeStreamProcessorRequestOps
    with ToDescribeStreamProcessorResponseOps
    with ToDetectFacesRequestOps
    with ToDetectFacesResponseOps
    with ToDetectLabelsRequestOps
    with ToDetectLabelsResponseOps
    with ToDetectModerationLabelsRequestOps
    with ToDetectModerationLabelsResponseOps
    with ToDetectTextRequestOps
    with ToDetectTextResponseOps
    with ToEmotionOps
    with ToEyeOpenOps
    with ToEyeglassesOps
    with ToFaceDetailOps
    with ToFaceDetectionOps
    with ToFaceMatchOps
    with ToFaceOps
    with ToFaceRecordOps
    with ToFaceSearchSettingsOps
    with ToGenderOps
    with ToGeometryOps
    with ToGetCelebrityInfoRequestOps
    with ToGetCelebrityInfoResponseOps
    with ToGetCelebrityRecognitionRequestOps
    with ToGetCelebrityRecognitionResponseOps
    with ToGetContentModerationRequestOps
    with ToGetContentModerationResponseOps
    with ToGetFaceDetectionRequestOps
    with ToGetFaceDetectionResponseOps
    with ToGetFaceSearchRequestOps
    with ToGetFaceSearchResponseOps
    with ToGetLabelDetectionRequestOps
    with ToGetLabelDetectionResponseOps
    with ToGetPersonTrackingRequestOps
    with ToGetPersonTrackingResponseOps
    with ToImageOps
    with ToImageQualityOps
    with ToIndexFacesRequestOps
    with ToIndexFacesResponseOps
    with ToInstanceOps
    with ToKinesisDataStreamOps
    with ToKinesisVideoStreamOps
    with ToLabelDetectionOps
    with ToLabelOps
    with ToLandmarkOps
    with ToListCollectionsRequestOps
    with ToListCollectionsResponseOps
    with ToListFacesRequestOps
    with ToListFacesResponseOps
    with ToListStreamProcessorsRequestOps
    with ToListStreamProcessorsResponseOps
    with ToModerationLabelOps
    with ToMouthOpenOps
    with ToMustacheOps
    with ToNotificationChannelOps
    with ToParentOps
    with ToPersonDetailOps
    with ToPersonDetectionOps
    with ToPersonMatchOps
    with ToPointOps
    with ToPoseOps
    with ToRecognizeCelebritiesRequestOps
    with ToRecognizeCelebritiesResponseOps
    with ToS3ObjectOps
    with ToSearchFacesByImageRequestOps
    with ToSearchFacesByImageResponseOps
    with ToSearchFacesRequestOps
    with ToSearchFacesResponseOps
    with ToSmileOps
    with ToStartCelebrityRecognitionRequestOps
    with ToStartCelebrityRecognitionResponseOps
    with ToStartContentModerationRequestOps
    with ToStartContentModerationResponseOps
    with ToStartFaceDetectionRequestOps
    with ToStartFaceDetectionResponseOps
    with ToStartFaceSearchRequestOps
    with ToStartFaceSearchResponseOps
    with ToStartLabelDetectionRequestOps
    with ToStartLabelDetectionResponseOps
    with ToStartPersonTrackingRequestOps
    with ToStartPersonTrackingResponseOps
    with ToStartStreamProcessorRequestOps
    with ToStopStreamProcessorRequestOps
    with ToStreamProcessorInputOps
    with ToStreamProcessorOps
    with ToStreamProcessorOutputOps
    with ToStreamProcessorSettingsOps
    with ToSunglassesOps
    with ToTextDetectionOps
    with ToUnindexedFaceOps
    with ToVideoMetadataOps
    with ToVideoOps
