package com.github.j5ik2o.reactive.aws.s3.model

final case class CopyObjectRequest(
    acl: Option[ObjectCannedACL] = None,
    bucket: Option[String] = None,
    cacheControl: Option[String] = None,
    contentDisposition: Option[String] = None,
    contentEncoding: Option[String] = None,
    contentLanguage: Option[String] = None,
    contentType: Option[String] = None,
    copySource: Option[String] = None,
    copySourceIfMatch: Option[String] = None,
    copySourceIfModifiedSince: Option[java.time.Instant] = None,
    copySourceIfNoneMatch: Option[String] = None,
    copySourceIfUnmodifiedSince: Option[java.time.Instant] = None,
    expires: Option[java.time.Instant] = None,
    grantFullControl: Option[String] = None,
    grantRead: Option[String] = None,
    grantReadACP: Option[String] = None,
    grantWriteACP: Option[String] = None,
    key: Option[String] = None,
    metadata: Option[Map[String, String]] = None,
    metadataDirective: Option[MetadataDirective] = None,
    taggingDirective: Option[TaggingDirective] = None,
    serverSideEncryption: Option[ServerSideEncryption] = None,
    storageClass: Option[StorageClass] = None,
    websiteRedirectLocation: Option[String] = None,
    sseCustomerAlgorithm: Option[String] = None,
    sseCustomerKey: Option[String] = None,
    sseCustomerKeyMD5: Option[String] = None,
    ssekmsKeyId: Option[String] = None,
    copySourceSSECustomerAlgorithm: Option[String] = None,
    copySourceSSECustomerKey: Option[String] = None,
    copySourceSSECustomerKeyMD5: Option[String] = None,
    requestPayer: Option[RequestPayer] = None,
    tagging: Option[String] = None,
    objectLockMode: Option[ObjectLockMode] = None,
    objectLockRetainUntilDate: Option[java.time.Instant] = None,
    objectLockLegalHoldStatus: Option[ObjectLockLegalHoldStatus] = None
) {
  def withAcl(value: Option[ObjectCannedACL]): CopyObjectRequest =
    copy(acl = value)
  def withBucket(value: Option[String]): CopyObjectRequest =
    copy(bucket = value)
  def withCacheControl(value: Option[String]): CopyObjectRequest =
    copy(cacheControl = value)
  def withContentDisposition(value: Option[String]): CopyObjectRequest =
    copy(contentDisposition = value)
  def withContentEncoding(value: Option[String]): CopyObjectRequest =
    copy(contentEncoding = value)
  def withContentLanguage(value: Option[String]): CopyObjectRequest =
    copy(contentLanguage = value)
  def withContentType(value: Option[String]): CopyObjectRequest =
    copy(contentType = value)
  def withCopySource(value: Option[String]): CopyObjectRequest =
    copy(copySource = value)
  def withCopySourceIfMatch(value: Option[String]): CopyObjectRequest =
    copy(copySourceIfMatch = value)
  def withCopySourceIfModifiedSince(value: Option[java.time.Instant]): CopyObjectRequest =
    copy(copySourceIfModifiedSince = value)
  def withCopySourceIfNoneMatch(value: Option[String]): CopyObjectRequest =
    copy(copySourceIfNoneMatch = value)
  def withCopySourceIfUnmodifiedSince(value: Option[java.time.Instant]): CopyObjectRequest =
    copy(copySourceIfUnmodifiedSince = value)
  def withExpires(value: Option[java.time.Instant]): CopyObjectRequest =
    copy(expires = value)
  def withGrantFullControl(value: Option[String]): CopyObjectRequest =
    copy(grantFullControl = value)
  def withGrantRead(value: Option[String]): CopyObjectRequest =
    copy(grantRead = value)
  def withGrantReadACP(value: Option[String]): CopyObjectRequest =
    copy(grantReadACP = value)
  def withGrantWriteACP(value: Option[String]): CopyObjectRequest =
    copy(grantWriteACP = value)
  def withKey(value: Option[String]): CopyObjectRequest =
    copy(key = value)
  def withMetadata(value: Option[Map[String, String]]): CopyObjectRequest =
    copy(metadata = value)
  def withMetadataDirective(value: Option[MetadataDirective]): CopyObjectRequest =
    copy(metadataDirective = value)
  def withTaggingDirective(value: Option[TaggingDirective]): CopyObjectRequest =
    copy(taggingDirective = value)
  def withServerSideEncryption(value: Option[ServerSideEncryption]): CopyObjectRequest =
    copy(serverSideEncryption = value)
  def withStorageClass(value: Option[StorageClass]): CopyObjectRequest =
    copy(storageClass = value)
  def withWebsiteRedirectLocation(value: Option[String]): CopyObjectRequest =
    copy(websiteRedirectLocation = value)
  def withSseCustomerAlgorithm(value: Option[String]): CopyObjectRequest =
    copy(sseCustomerAlgorithm = value)
  def withSseCustomerKey(value: Option[String]): CopyObjectRequest =
    copy(sseCustomerKey = value)
  def withSseCustomerKeyMD5(value: Option[String]): CopyObjectRequest =
    copy(sseCustomerKeyMD5 = value)
  def withSsekmsKeyId(value: Option[String]): CopyObjectRequest =
    copy(ssekmsKeyId = value)
  def withCopySourceSSECustomerAlgorithm(value: Option[String]): CopyObjectRequest =
    copy(copySourceSSECustomerAlgorithm = value)
  def withCopySourceSSECustomerKey(value: Option[String]): CopyObjectRequest =
    copy(copySourceSSECustomerKey = value)
  def withCopySourceSSECustomerKeyMD5(value: Option[String]): CopyObjectRequest =
    copy(copySourceSSECustomerKeyMD5 = value)
  def withRequestPayer(value: Option[RequestPayer]): CopyObjectRequest =
    copy(requestPayer = value)
  def withTagging(value: Option[String]): CopyObjectRequest =
    copy(tagging = value)
  def withObjectLockMode(value: Option[ObjectLockMode]): CopyObjectRequest =
    copy(objectLockMode = value)
  def withObjectLockRetainUntilDate(value: Option[java.time.Instant]): CopyObjectRequest =
    copy(objectLockRetainUntilDate = value)
  def withObjectLockLegalHoldStatus(value: Option[ObjectLockLegalHoldStatus]): CopyObjectRequest =
    copy(objectLockLegalHoldStatus = value)
}
