package com.github.j5ik2o.reactive.aws.s3.model

final case class GetObjectRequest(
    bucket: Option[String] = None,
    ifMatch: Option[String] = None,
    ifModifiedSince: Option[java.time.Instant] = None,
    ifNoneMatch: Option[String] = None,
    ifUnmodifiedSince: Option[java.time.Instant] = None,
    key: Option[String] = None,
    range: Option[String] = None,
    responseCacheControl: Option[String] = None,
    responseContentDisposition: Option[String] = None,
    responseContentEncoding: Option[String] = None,
    responseContentLanguage: Option[String] = None,
    responseContentType: Option[String] = None,
    responseExpires: Option[java.time.Instant] = None,
    versionId: Option[String] = None,
    sseCustomerAlgorithm: Option[String] = None,
    sseCustomerKey: Option[String] = None,
    sseCustomerKeyMD5: Option[String] = None,
    requestPayer: Option[RequestPayer] = None,
    partNumber: Option[Int] = None
) {
  def withBucket(value: Option[String]): GetObjectRequest =
    copy(bucket = value)
  def withIfMatch(value: Option[String]): GetObjectRequest =
    copy(ifMatch = value)
  def withIfModifiedSince(value: Option[java.time.Instant]): GetObjectRequest =
    copy(ifModifiedSince = value)
  def withIfNoneMatch(value: Option[String]): GetObjectRequest =
    copy(ifNoneMatch = value)
  def withIfUnmodifiedSince(value: Option[java.time.Instant]): GetObjectRequest =
    copy(ifUnmodifiedSince = value)
  def withKey(value: Option[String]): GetObjectRequest =
    copy(key = value)
  def withRange(value: Option[String]): GetObjectRequest =
    copy(range = value)
  def withResponseCacheControl(value: Option[String]): GetObjectRequest =
    copy(responseCacheControl = value)
  def withResponseContentDisposition(value: Option[String]): GetObjectRequest =
    copy(responseContentDisposition = value)
  def withResponseContentEncoding(value: Option[String]): GetObjectRequest =
    copy(responseContentEncoding = value)
  def withResponseContentLanguage(value: Option[String]): GetObjectRequest =
    copy(responseContentLanguage = value)
  def withResponseContentType(value: Option[String]): GetObjectRequest =
    copy(responseContentType = value)
  def withResponseExpires(value: Option[java.time.Instant]): GetObjectRequest =
    copy(responseExpires = value)
  def withVersionId(value: Option[String]): GetObjectRequest =
    copy(versionId = value)
  def withSseCustomerAlgorithm(value: Option[String]): GetObjectRequest =
    copy(sseCustomerAlgorithm = value)
  def withSseCustomerKey(value: Option[String]): GetObjectRequest =
    copy(sseCustomerKey = value)
  def withSseCustomerKeyMD5(value: Option[String]): GetObjectRequest =
    copy(sseCustomerKeyMD5 = value)
  def withRequestPayer(value: Option[RequestPayer]): GetObjectRequest =
    copy(requestPayer = value)
  def withPartNumber(value: Option[Int]): GetObjectRequest =
    copy(partNumber = value)
}
