package com.github.j5ik2o.reactive.aws.s3.model

import com.github.j5ik2o.reactive.aws.model.AbstractResponse

final case class GetObjectResponse(
    override val statusCode: Option[Int] = None,
    override val statusText: Option[String] = None,
    override val httpHeaders: Option[Map[String, Seq[String]]] = None,
    deleteMarker: Option[Boolean] = None,
    acceptRanges: Option[String] = None,
    expiration: Option[String] = None,
    restore: Option[String] = None,
    lastModified: Option[java.time.Instant] = None,
    contentLength: Option[Long] = None,
    eTag: Option[String] = None,
    missingMeta: Option[Int] = None,
    versionId: Option[String] = None,
    cacheControl: Option[String] = None,
    contentDisposition: Option[String] = None,
    contentEncoding: Option[String] = None,
    contentLanguage: Option[String] = None,
    contentRange: Option[String] = None,
    contentType: Option[String] = None,
    expires: Option[java.time.Instant] = None,
    websiteRedirectLocation: Option[String] = None,
    serverSideEncryption: Option[ServerSideEncryption] = None,
    metadata: Option[Map[String, String]] = None,
    sseCustomerAlgorithm: Option[String] = None,
    sseCustomerKeyMD5: Option[String] = None,
    ssekmsKeyId: Option[String] = None,
    storageClass: Option[StorageClass] = None,
    requestCharged: Option[RequestCharged] = None,
    replicationStatus: Option[ReplicationStatus] = None,
    partsCount: Option[Int] = None,
    tagCount: Option[Int] = None,
    objectLockMode: Option[ObjectLockMode] = None,
    objectLockRetainUntilDate: Option[java.time.Instant] = None,
    objectLockLegalHoldStatus: Option[ObjectLockLegalHoldStatus] = None
) extends AbstractResponse(statusCode, statusText, httpHeaders) {
  override type ThisType = GetObjectResponse
  override def withStatusCode(value: Option[Int]): GetObjectResponse    = copy(statusCode = value)
  override def withStatusText(value: Option[String]): GetObjectResponse = copy(statusText = value)
  override def withHttpHeaders(value: Option[Map[String, Seq[String]]]): GetObjectResponse =
    copy(httpHeaders = value)
  def withDeleteMarker(value: Option[Boolean]): GetObjectResponse =
    copy(deleteMarker = value)
  def withAcceptRanges(value: Option[String]): GetObjectResponse =
    copy(acceptRanges = value)
  def withExpiration(value: Option[String]): GetObjectResponse =
    copy(expiration = value)
  def withRestore(value: Option[String]): GetObjectResponse =
    copy(restore = value)
  def withLastModified(value: Option[java.time.Instant]): GetObjectResponse =
    copy(lastModified = value)
  def withContentLength(value: Option[Long]): GetObjectResponse =
    copy(contentLength = value)
  def withETag(value: Option[String]): GetObjectResponse =
    copy(eTag = value)
  def withMissingMeta(value: Option[Int]): GetObjectResponse =
    copy(missingMeta = value)
  def withVersionId(value: Option[String]): GetObjectResponse =
    copy(versionId = value)
  def withCacheControl(value: Option[String]): GetObjectResponse =
    copy(cacheControl = value)
  def withContentDisposition(value: Option[String]): GetObjectResponse =
    copy(contentDisposition = value)
  def withContentEncoding(value: Option[String]): GetObjectResponse =
    copy(contentEncoding = value)
  def withContentLanguage(value: Option[String]): GetObjectResponse =
    copy(contentLanguage = value)
  def withContentRange(value: Option[String]): GetObjectResponse =
    copy(contentRange = value)
  def withContentType(value: Option[String]): GetObjectResponse =
    copy(contentType = value)
  def withExpires(value: Option[java.time.Instant]): GetObjectResponse =
    copy(expires = value)
  def withWebsiteRedirectLocation(value: Option[String]): GetObjectResponse =
    copy(websiteRedirectLocation = value)
  def withServerSideEncryption(value: Option[ServerSideEncryption]): GetObjectResponse =
    copy(serverSideEncryption = value)
  def withMetadata(value: Option[Map[String, String]]): GetObjectResponse =
    copy(metadata = value)
  def withSseCustomerAlgorithm(value: Option[String]): GetObjectResponse =
    copy(sseCustomerAlgorithm = value)
  def withSseCustomerKeyMD5(value: Option[String]): GetObjectResponse =
    copy(sseCustomerKeyMD5 = value)
  def withSsekmsKeyId(value: Option[String]): GetObjectResponse =
    copy(ssekmsKeyId = value)
  def withStorageClass(value: Option[StorageClass]): GetObjectResponse =
    copy(storageClass = value)
  def withRequestCharged(value: Option[RequestCharged]): GetObjectResponse =
    copy(requestCharged = value)
  def withReplicationStatus(value: Option[ReplicationStatus]): GetObjectResponse =
    copy(replicationStatus = value)
  def withPartsCount(value: Option[Int]): GetObjectResponse =
    copy(partsCount = value)
  def withTagCount(value: Option[Int]): GetObjectResponse =
    copy(tagCount = value)
  def withObjectLockMode(value: Option[ObjectLockMode]): GetObjectResponse =
    copy(objectLockMode = value)
  def withObjectLockRetainUntilDate(value: Option[java.time.Instant]): GetObjectResponse =
    copy(objectLockRetainUntilDate = value)
  def withObjectLockLegalHoldStatus(value: Option[ObjectLockLegalHoldStatus]): GetObjectResponse =
    copy(objectLockLegalHoldStatus = value)
}
