package com.github.j5ik2o.reactive.aws.s3.model

final case class PutObjectRequest(
    acl: Option[ObjectCannedACL] = None,
    bucket: Option[String] = None,
    cacheControl: Option[String] = None,
    contentDisposition: Option[String] = None,
    contentEncoding: Option[String] = None,
    contentLanguage: Option[String] = None,
    contentLength: Option[Long] = None,
    contentMD5: Option[String] = None,
    contentType: Option[String] = None,
    expires: Option[java.time.Instant] = None,
    grantFullControl: Option[String] = None,
    grantRead: Option[String] = None,
    grantReadACP: Option[String] = None,
    grantWriteACP: Option[String] = None,
    key: Option[String] = None,
    metadata: Option[Map[String, String]] = None,
    serverSideEncryption: Option[ServerSideEncryption] = None,
    storageClass: Option[StorageClass] = None,
    websiteRedirectLocation: Option[String] = None,
    sseCustomerAlgorithm: Option[String] = None,
    sseCustomerKey: Option[String] = None,
    sseCustomerKeyMD5: Option[String] = None,
    ssekmsKeyId: Option[String] = None,
    requestPayer: Option[RequestPayer] = None,
    tagging: Option[String] = None,
    objectLockMode: Option[ObjectLockMode] = None,
    objectLockRetainUntilDate: Option[java.time.Instant] = None,
    objectLockLegalHoldStatus: Option[ObjectLockLegalHoldStatus] = None
) {
  def withAcl(value: Option[ObjectCannedACL]): PutObjectRequest =
    copy(acl = value)
  def withBucket(value: Option[String]): PutObjectRequest =
    copy(bucket = value)
  def withCacheControl(value: Option[String]): PutObjectRequest =
    copy(cacheControl = value)
  def withContentDisposition(value: Option[String]): PutObjectRequest =
    copy(contentDisposition = value)
  def withContentEncoding(value: Option[String]): PutObjectRequest =
    copy(contentEncoding = value)
  def withContentLanguage(value: Option[String]): PutObjectRequest =
    copy(contentLanguage = value)
  def withContentLength(value: Option[Long]): PutObjectRequest =
    copy(contentLength = value)
  def withContentMD5(value: Option[String]): PutObjectRequest =
    copy(contentMD5 = value)
  def withContentType(value: Option[String]): PutObjectRequest =
    copy(contentType = value)
  def withExpires(value: Option[java.time.Instant]): PutObjectRequest =
    copy(expires = value)
  def withGrantFullControl(value: Option[String]): PutObjectRequest =
    copy(grantFullControl = value)
  def withGrantRead(value: Option[String]): PutObjectRequest =
    copy(grantRead = value)
  def withGrantReadACP(value: Option[String]): PutObjectRequest =
    copy(grantReadACP = value)
  def withGrantWriteACP(value: Option[String]): PutObjectRequest =
    copy(grantWriteACP = value)
  def withKey(value: Option[String]): PutObjectRequest =
    copy(key = value)
  def withMetadata(value: Option[Map[String, String]]): PutObjectRequest =
    copy(metadata = value)
  def withServerSideEncryption(value: Option[ServerSideEncryption]): PutObjectRequest =
    copy(serverSideEncryption = value)
  def withStorageClass(value: Option[StorageClass]): PutObjectRequest =
    copy(storageClass = value)
  def withWebsiteRedirectLocation(value: Option[String]): PutObjectRequest =
    copy(websiteRedirectLocation = value)
  def withSseCustomerAlgorithm(value: Option[String]): PutObjectRequest =
    copy(sseCustomerAlgorithm = value)
  def withSseCustomerKey(value: Option[String]): PutObjectRequest =
    copy(sseCustomerKey = value)
  def withSseCustomerKeyMD5(value: Option[String]): PutObjectRequest =
    copy(sseCustomerKeyMD5 = value)
  def withSsekmsKeyId(value: Option[String]): PutObjectRequest =
    copy(ssekmsKeyId = value)
  def withRequestPayer(value: Option[RequestPayer]): PutObjectRequest =
    copy(requestPayer = value)
  def withTagging(value: Option[String]): PutObjectRequest =
    copy(tagging = value)
  def withObjectLockMode(value: Option[ObjectLockMode]): PutObjectRequest =
    copy(objectLockMode = value)
  def withObjectLockRetainUntilDate(value: Option[java.time.Instant]): PutObjectRequest =
    copy(objectLockRetainUntilDate = value)
  def withObjectLockLegalHoldStatus(value: Option[ObjectLockLegalHoldStatus]): PutObjectRequest =
    copy(objectLockLegalHoldStatus = value)
}
