package com.github.j5ik2o.reactive.aws.ecs.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToAttachmentOps
    with ToAttachmentStateChangeOps
    with ToAttributeOps
    with ToAwsVpcConfigurationOps
    with ToClusterOps
    with ToContainerDefinitionOps
    with ToContainerInstanceOps
    with ToContainerOps
    with ToContainerOverrideOps
    with ToContainerStateChangeOps
    with ToCreateClusterRequestOps
    with ToCreateClusterResponseOps
    with ToCreateServiceRequestOps
    with ToCreateServiceResponseOps
    with ToDeleteAccountSettingRequestOps
    with ToDeleteAccountSettingResponseOps
    with ToDeleteAttributesRequestOps
    with ToDeleteAttributesResponseOps
    with ToDeleteClusterRequestOps
    with ToDeleteClusterResponseOps
    with ToDeleteServiceRequestOps
    with ToDeleteServiceResponseOps
    with ToDeploymentConfigurationOps
    with ToDeploymentControllerOps
    with ToDeploymentOps
    with ToDeregisterContainerInstanceRequestOps
    with ToDeregisterContainerInstanceResponseOps
    with ToDeregisterTaskDefinitionRequestOps
    with ToDeregisterTaskDefinitionResponseOps
    with ToDescribeClustersRequestOps
    with ToDescribeClustersResponseOps
    with ToDescribeContainerInstancesRequestOps
    with ToDescribeContainerInstancesResponseOps
    with ToDescribeServicesRequestOps
    with ToDescribeServicesResponseOps
    with ToDescribeTaskDefinitionRequestOps
    with ToDescribeTaskDefinitionResponseOps
    with ToDescribeTasksRequestOps
    with ToDescribeTasksResponseOps
    with ToDeviceOps
    with ToDiscoverPollEndpointRequestOps
    with ToDiscoverPollEndpointResponseOps
    with ToDockerVolumeConfigurationOps
    with ToFailureOps
    with ToHealthCheckOps
    with ToHostEntryOps
    with ToHostVolumePropertiesOps
    with ToKernelCapabilitiesOps
    with ToKeyValuePairOps
    with ToLinuxParametersOps
    with ToListAccountSettingsRequestOps
    with ToListAccountSettingsResponseOps
    with ToListAttributesRequestOps
    with ToListAttributesResponseOps
    with ToListClustersRequestOps
    with ToListClustersResponseOps
    with ToListContainerInstancesRequestOps
    with ToListContainerInstancesResponseOps
    with ToListServicesRequestOps
    with ToListServicesResponseOps
    with ToListTagsForResourceRequestOps
    with ToListTagsForResourceResponseOps
    with ToListTaskDefinitionFamiliesRequestOps
    with ToListTaskDefinitionFamiliesResponseOps
    with ToListTaskDefinitionsRequestOps
    with ToListTaskDefinitionsResponseOps
    with ToListTasksRequestOps
    with ToListTasksResponseOps
    with ToLoadBalancerOps
    with ToLogConfigurationOps
    with ToMountPointOps
    with ToNetworkBindingOps
    with ToNetworkConfigurationOps
    with ToNetworkInterfaceOps
    with ToPlacementConstraintOps
    with ToPlacementStrategyOps
    with ToPlatformDeviceOps
    with ToPortMappingOps
    with ToPutAccountSettingDefaultRequestOps
    with ToPutAccountSettingDefaultResponseOps
    with ToPutAccountSettingRequestOps
    with ToPutAccountSettingResponseOps
    with ToPutAttributesRequestOps
    with ToPutAttributesResponseOps
    with ToRegisterContainerInstanceRequestOps
    with ToRegisterContainerInstanceResponseOps
    with ToRegisterTaskDefinitionRequestOps
    with ToRegisterTaskDefinitionResponseOps
    with ToRepositoryCredentialsOps
    with ToResourceOps
    with ToResourceRequirementOps
    with ToRunTaskRequestOps
    with ToRunTaskResponseOps
    with ToScaleOps
    with ToSecretOps
    with ToServiceEventOps
    with ToServiceOps
    with ToServiceRegistryOps
    with ToSettingOps
    with ToStartTaskRequestOps
    with ToStartTaskResponseOps
    with ToStopTaskRequestOps
    with ToStopTaskResponseOps
    with ToSubmitContainerStateChangeRequestOps
    with ToSubmitContainerStateChangeResponseOps
    with ToSubmitTaskStateChangeRequestOps
    with ToSubmitTaskStateChangeResponseOps
    with ToSystemControlOps
    with ToTagOps
    with ToTagResourceRequestOps
    with ToTagResourceResponseOps
    with ToTaskDefinitionOps
    with ToTaskDefinitionPlacementConstraintOps
    with ToTaskOps
    with ToTaskOverrideOps
    with ToTaskSetOps
    with ToTmpfsOps
    with ToUlimitOps
    with ToUntagResourceRequestOps
    with ToUntagResourceResponseOps
    with ToUpdateContainerAgentRequestOps
    with ToUpdateContainerAgentResponseOps
    with ToUpdateContainerInstancesStateRequestOps
    with ToUpdateContainerInstancesStateResponseOps
    with ToUpdateServiceRequestOps
    with ToUpdateServiceResponseOps
    with ToVersionInfoOps
    with ToVolumeFromOps
    with ToVolumeOps
