package com.github.j5ik2o.reactive.aws.batch.model.ops

trait ToAllOps
    extends ToArrayPropertiesDetailOps
    with ToArrayPropertiesOps
    with ToArrayPropertiesSummaryOps
    with ToAttemptContainerDetailOps
    with ToAttemptDetailOps
    with ToCancelJobRequestOps
    with ToComputeEnvironmentDetailOps
    with ToComputeEnvironmentOrderOps
    with ToComputeResourceOps
    with ToComputeResourceUpdateOps
    with ToContainerDetailOps
    with ToContainerOverridesOps
    with ToContainerPropertiesOps
    with ToContainerSummaryOps
    with ToCreateComputeEnvironmentRequestOps
    with ToCreateComputeEnvironmentResponseOps
    with ToCreateJobQueueRequestOps
    with ToCreateJobQueueResponseOps
    with ToDeleteComputeEnvironmentRequestOps
    with ToDeleteJobQueueRequestOps
    with ToDeregisterJobDefinitionRequestOps
    with ToDescribeComputeEnvironmentsRequestOps
    with ToDescribeComputeEnvironmentsResponseOps
    with ToDescribeJobDefinitionsRequestOps
    with ToDescribeJobDefinitionsResponseOps
    with ToDescribeJobQueuesRequestOps
    with ToDescribeJobQueuesResponseOps
    with ToDescribeJobsRequestOps
    with ToDescribeJobsResponseOps
    with ToHostOps
    with ToJobDefinitionOps
    with ToJobDependencyOps
    with ToJobDetailOps
    with ToJobQueueDetailOps
    with ToJobSummaryOps
    with ToJobTimeoutOps
    with ToKeyValuePairOps
    with ToLaunchTemplateSpecificationOps
    with ToListJobsRequestOps
    with ToListJobsResponseOps
    with ToMountPointOps
    with ToNetworkInterfaceOps
    with ToNodeDetailsOps
    with ToNodeOverridesOps
    with ToNodePropertiesOps
    with ToNodePropertiesSummaryOps
    with ToNodePropertyOverrideOps
    with ToNodeRangePropertyOps
    with ToRegisterJobDefinitionRequestOps
    with ToRegisterJobDefinitionResponseOps
    with ToRetryStrategyOps
    with ToSubmitJobRequestOps
    with ToSubmitJobResponseOps
    with ToTerminateJobRequestOps
    with ToUlimitOps
    with ToUpdateComputeEnvironmentRequestOps
    with ToUpdateComputeEnvironmentResponseOps
    with ToUpdateJobQueueRequestOps
    with ToUpdateJobQueueResponseOps
    with ToVolumeOps
