package com.github.j5ik2o.reactive.aws.kinesis.model.ops

trait ToAllOps
    extends ToAddTagsToStreamRequestOps
    with ToAddTagsToStreamResponseOps
    with ToConsumerDescriptionOps
    with ToConsumerOps
    with ToCreateStreamRequestOps
    with ToCreateStreamResponseOps
    with ToDecreaseStreamRetentionPeriodRequestOps
    with ToDecreaseStreamRetentionPeriodResponseOps
    with ToDeleteStreamRequestOps
    with ToDeleteStreamResponseOps
    with ToDeregisterStreamConsumerRequestOps
    with ToDeregisterStreamConsumerResponseOps
    with ToDescribeLimitsRequestOps
    with ToDescribeLimitsResponseOps
    with ToDescribeStreamConsumerRequestOps
    with ToDescribeStreamConsumerResponseOps
    with ToDescribeStreamRequestOps
    with ToDescribeStreamResponseOps
    with ToDescribeStreamSummaryRequestOps
    with ToDescribeStreamSummaryResponseOps
    with ToDisableEnhancedMonitoringRequestOps
    with ToDisableEnhancedMonitoringResponseOps
    with ToEnableEnhancedMonitoringRequestOps
    with ToEnableEnhancedMonitoringResponseOps
    with ToEnhancedMetricsOps
    with ToGetRecordsRequestOps
    with ToGetRecordsResponseOps
    with ToGetShardIteratorRequestOps
    with ToGetShardIteratorResponseOps
    with ToHashKeyRangeOps
    with ToIncreaseStreamRetentionPeriodRequestOps
    with ToIncreaseStreamRetentionPeriodResponseOps
    with ToListShardsRequestOps
    with ToListShardsResponseOps
    with ToListStreamConsumersRequestOps
    with ToListStreamConsumersResponseOps
    with ToListStreamsRequestOps
    with ToListStreamsResponseOps
    with ToListTagsForStreamRequestOps
    with ToListTagsForStreamResponseOps
    with ToMergeShardsRequestOps
    with ToMergeShardsResponseOps
    with ToPutRecordRequestOps
    with ToPutRecordResponseOps
    with ToPutRecordsRequestEntryOps
    with ToPutRecordsRequestOps
    with ToPutRecordsResponseOps
    with ToPutRecordsResultEntryOps
    with ToRecordOps
    with ToRegisterStreamConsumerRequestOps
    with ToRegisterStreamConsumerResponseOps
    with ToRemoveTagsFromStreamRequestOps
    with ToRemoveTagsFromStreamResponseOps
    with ToSequenceNumberRangeOps
    with ToShardOps
    with ToSplitShardRequestOps
    with ToSplitShardResponseOps
    with ToStartStreamEncryptionRequestOps
    with ToStartStreamEncryptionResponseOps
    with ToStartingPositionOps
    with ToStopStreamEncryptionRequestOps
    with ToStopStreamEncryptionResponseOps
    with ToStreamDescriptionOps
    with ToStreamDescriptionSummaryOps
    with ToSubscribeToShardEventOps
    with ToSubscribeToShardRequestOps
    with ToSubscribeToShardResponseOps
    with ToTagOps
    with ToUpdateShardCountRequestOps
    with ToUpdateShardCountResponseOps
