package com.github.j5ik2o.reactive.aws.ec2.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToAcceptReservedInstancesExchangeQuoteRequestOps
    with ToAcceptReservedInstancesExchangeQuoteResponseOps
    with ToAcceptTransitGatewayPeeringAttachmentRequestOps
    with ToAcceptTransitGatewayPeeringAttachmentResponseOps
    with ToAcceptTransitGatewayVpcAttachmentRequestOps
    with ToAcceptTransitGatewayVpcAttachmentResponseOps
    with ToAcceptVpcEndpointConnectionsRequestOps
    with ToAcceptVpcEndpointConnectionsResponseOps
    with ToAcceptVpcPeeringConnectionRequestOps
    with ToAcceptVpcPeeringConnectionResponseOps
    with ToAccountAttributeOps
    with ToAccountAttributeValueOps
    with ToActiveInstanceOps
    with ToAddressOps
    with ToAdvertiseByoipCidrRequestOps
    with ToAdvertiseByoipCidrResponseOps
    with ToAllocateAddressRequestOps
    with ToAllocateAddressResponseOps
    with ToAllocateHostsRequestOps
    with ToAllocateHostsResponseOps
    with ToAllowedPrincipalOps
    with ToApplySecurityGroupsToClientVpnTargetNetworkRequestOps
    with ToApplySecurityGroupsToClientVpnTargetNetworkResponseOps
    with ToAssignIpv6AddressesRequestOps
    with ToAssignIpv6AddressesResponseOps
    with ToAssignPrivateIpAddressesRequestOps
    with ToAssignPrivateIpAddressesResponseOps
    with ToAssignedPrivateIpAddressOps
    with ToAssociateAddressRequestOps
    with ToAssociateAddressResponseOps
    with ToAssociateClientVpnTargetNetworkRequestOps
    with ToAssociateClientVpnTargetNetworkResponseOps
    with ToAssociateDhcpOptionsRequestOps
    with ToAssociateIamInstanceProfileRequestOps
    with ToAssociateIamInstanceProfileResponseOps
    with ToAssociateRouteTableRequestOps
    with ToAssociateRouteTableResponseOps
    with ToAssociateSubnetCidrBlockRequestOps
    with ToAssociateSubnetCidrBlockResponseOps
    with ToAssociateTransitGatewayMulticastDomainRequestOps
    with ToAssociateTransitGatewayMulticastDomainResponseOps
    with ToAssociateTransitGatewayRouteTableRequestOps
    with ToAssociateTransitGatewayRouteTableResponseOps
    with ToAssociateVpcCidrBlockRequestOps
    with ToAssociateVpcCidrBlockResponseOps
    with ToAssociatedTargetNetworkOps
    with ToAssociationStatusOps
    with ToAttachClassicLinkVpcRequestOps
    with ToAttachClassicLinkVpcResponseOps
    with ToAttachInternetGatewayRequestOps
    with ToAttachNetworkInterfaceRequestOps
    with ToAttachNetworkInterfaceResponseOps
    with ToAttachVolumeRequestOps
    with ToAttachVolumeResponseOps
    with ToAttachVpnGatewayRequestOps
    with ToAttachVpnGatewayResponseOps
    with ToAttributeBooleanValueOps
    with ToAttributeValueOps
    with ToAuthorizationRuleOps
    with ToAuthorizeClientVpnIngressRequestOps
    with ToAuthorizeClientVpnIngressResponseOps
    with ToAuthorizeSecurityGroupEgressRequestOps
    with ToAuthorizeSecurityGroupIngressRequestOps
    with ToAvailabilityZoneMessageOps
    with ToAvailabilityZoneOps
    with ToAvailableCapacityOps
    with ToBlobAttributeValueOps
    with ToBlockDeviceMappingOps
    with ToBundleInstanceRequestOps
    with ToBundleInstanceResponseOps
    with ToBundleTaskErrorOps
    with ToBundleTaskOps
    with ToByoipCidrOps
    with ToCancelBundleTaskRequestOps
    with ToCancelBundleTaskResponseOps
    with ToCancelCapacityReservationRequestOps
    with ToCancelCapacityReservationResponseOps
    with ToCancelConversionTaskRequestOps
    with ToCancelExportTaskRequestOps
    with ToCancelImportTaskRequestOps
    with ToCancelImportTaskResponseOps
    with ToCancelReservedInstancesListingRequestOps
    with ToCancelReservedInstancesListingResponseOps
    with ToCancelSpotFleetRequestsErrorItemOps
    with ToCancelSpotFleetRequestsErrorOps
    with ToCancelSpotFleetRequestsRequestOps
    with ToCancelSpotFleetRequestsResponseOps
    with ToCancelSpotFleetRequestsSuccessItemOps
    with ToCancelSpotInstanceRequestsRequestOps
    with ToCancelSpotInstanceRequestsResponseOps
    with ToCancelledSpotInstanceRequestOps
    with ToCapacityReservationOps
    with ToCapacityReservationOptionsOps
    with ToCapacityReservationOptionsRequestOps
    with ToCapacityReservationSpecificationOps
    with ToCapacityReservationSpecificationResponseOps
    with ToCapacityReservationTargetOps
    with ToCapacityReservationTargetResponseOps
    with ToCertificateAuthenticationOps
    with ToCertificateAuthenticationRequestOps
    with ToCidrAuthorizationContextOps
    with ToCidrBlockOps
    with ToClassicLinkDnsSupportOps
    with ToClassicLinkInstanceOps
    with ToClassicLoadBalancerOps
    with ToClassicLoadBalancersConfigOps
    with ToClientCertificateRevocationListStatusOps
    with ToClientDataOps
    with ToClientVpnAuthenticationOps
    with ToClientVpnAuthenticationRequestOps
    with ToClientVpnAuthorizationRuleStatusOps
    with ToClientVpnConnectionOps
    with ToClientVpnConnectionStatusOps
    with ToClientVpnEndpointOps
    with ToClientVpnEndpointStatusOps
    with ToClientVpnRouteOps
    with ToClientVpnRouteStatusOps
    with ToCoipAddressUsageOps
    with ToCoipPoolOps
    with ToConfirmProductInstanceRequestOps
    with ToConfirmProductInstanceResponseOps
    with ToConnectionLogOptionsOps
    with ToConnectionLogResponseOptionsOps
    with ToConnectionNotificationOps
    with ToConversionTaskOps
    with ToCopyFpgaImageRequestOps
    with ToCopyFpgaImageResponseOps
    with ToCopyImageRequestOps
    with ToCopyImageResponseOps
    with ToCopySnapshotRequestOps
    with ToCopySnapshotResponseOps
    with ToCpuOptionsOps
    with ToCpuOptionsRequestOps
    with ToCreateCapacityReservationRequestOps
    with ToCreateCapacityReservationResponseOps
    with ToCreateClientVpnEndpointRequestOps
    with ToCreateClientVpnEndpointResponseOps
    with ToCreateClientVpnRouteRequestOps
    with ToCreateClientVpnRouteResponseOps
    with ToCreateCustomerGatewayRequestOps
    with ToCreateCustomerGatewayResponseOps
    with ToCreateDefaultSubnetRequestOps
    with ToCreateDefaultSubnetResponseOps
    with ToCreateDefaultVpcResponseOps
    with ToCreateDhcpOptionsRequestOps
    with ToCreateDhcpOptionsResponseOps
    with ToCreateEgressOnlyInternetGatewayRequestOps
    with ToCreateEgressOnlyInternetGatewayResponseOps
    with ToCreateFleetErrorOps
    with ToCreateFleetInstanceOps
    with ToCreateFleetRequestOps
    with ToCreateFleetResponseOps
    with ToCreateFlowLogsRequestOps
    with ToCreateFlowLogsResponseOps
    with ToCreateFpgaImageRequestOps
    with ToCreateFpgaImageResponseOps
    with ToCreateImageRequestOps
    with ToCreateImageResponseOps
    with ToCreateInstanceExportTaskRequestOps
    with ToCreateInstanceExportTaskResponseOps
    with ToCreateInternetGatewayResponseOps
    with ToCreateKeyPairRequestOps
    with ToCreateKeyPairResponseOps
    with ToCreateLaunchTemplateRequestOps
    with ToCreateLaunchTemplateResponseOps
    with ToCreateLaunchTemplateVersionRequestOps
    with ToCreateLaunchTemplateVersionResponseOps
    with ToCreateLocalGatewayRouteRequestOps
    with ToCreateLocalGatewayRouteResponseOps
    with ToCreateLocalGatewayRouteTableVpcAssociationRequestOps
    with ToCreateLocalGatewayRouteTableVpcAssociationResponseOps
    with ToCreateNatGatewayRequestOps
    with ToCreateNatGatewayResponseOps
    with ToCreateNetworkAclEntryRequestOps
    with ToCreateNetworkAclRequestOps
    with ToCreateNetworkAclResponseOps
    with ToCreateNetworkInterfacePermissionRequestOps
    with ToCreateNetworkInterfacePermissionResponseOps
    with ToCreateNetworkInterfaceRequestOps
    with ToCreateNetworkInterfaceResponseOps
    with ToCreatePlacementGroupRequestOps
    with ToCreateReservedInstancesListingRequestOps
    with ToCreateReservedInstancesListingResponseOps
    with ToCreateRouteRequestOps
    with ToCreateRouteResponseOps
    with ToCreateRouteTableRequestOps
    with ToCreateRouteTableResponseOps
    with ToCreateSecurityGroupRequestOps
    with ToCreateSecurityGroupResponseOps
    with ToCreateSnapshotRequestOps
    with ToCreateSnapshotResponseOps
    with ToCreateSnapshotsRequestOps
    with ToCreateSnapshotsResponseOps
    with ToCreateSpotDatafeedSubscriptionRequestOps
    with ToCreateSpotDatafeedSubscriptionResponseOps
    with ToCreateSubnetRequestOps
    with ToCreateSubnetResponseOps
    with ToCreateTagsRequestOps
    with ToCreateTrafficMirrorFilterRequestOps
    with ToCreateTrafficMirrorFilterResponseOps
    with ToCreateTrafficMirrorFilterRuleRequestOps
    with ToCreateTrafficMirrorFilterRuleResponseOps
    with ToCreateTrafficMirrorSessionRequestOps
    with ToCreateTrafficMirrorSessionResponseOps
    with ToCreateTrafficMirrorTargetRequestOps
    with ToCreateTrafficMirrorTargetResponseOps
    with ToCreateTransitGatewayMulticastDomainRequestOps
    with ToCreateTransitGatewayMulticastDomainResponseOps
    with ToCreateTransitGatewayPeeringAttachmentRequestOps
    with ToCreateTransitGatewayPeeringAttachmentResponseOps
    with ToCreateTransitGatewayRequestOps
    with ToCreateTransitGatewayResponseOps
    with ToCreateTransitGatewayRouteRequestOps
    with ToCreateTransitGatewayRouteResponseOps
    with ToCreateTransitGatewayRouteTableRequestOps
    with ToCreateTransitGatewayRouteTableResponseOps
    with ToCreateTransitGatewayVpcAttachmentRequestOps
    with ToCreateTransitGatewayVpcAttachmentRequestOptionsOps
    with ToCreateTransitGatewayVpcAttachmentResponseOps
    with ToCreateVolumePermissionModificationsOps
    with ToCreateVolumePermissionOps
    with ToCreateVolumeRequestOps
    with ToCreateVolumeResponseOps
    with ToCreateVpcEndpointConnectionNotificationRequestOps
    with ToCreateVpcEndpointConnectionNotificationResponseOps
    with ToCreateVpcEndpointRequestOps
    with ToCreateVpcEndpointResponseOps
    with ToCreateVpcEndpointServiceConfigurationRequestOps
    with ToCreateVpcEndpointServiceConfigurationResponseOps
    with ToCreateVpcPeeringConnectionRequestOps
    with ToCreateVpcPeeringConnectionResponseOps
    with ToCreateVpcRequestOps
    with ToCreateVpcResponseOps
    with ToCreateVpnConnectionRequestOps
    with ToCreateVpnConnectionResponseOps
    with ToCreateVpnConnectionRouteRequestOps
    with ToCreateVpnGatewayRequestOps
    with ToCreateVpnGatewayResponseOps
    with ToCreditSpecificationOps
    with ToCreditSpecificationRequestOps
    with ToCustomerGatewayOps
    with ToDeleteClientVpnEndpointRequestOps
    with ToDeleteClientVpnEndpointResponseOps
    with ToDeleteClientVpnRouteRequestOps
    with ToDeleteClientVpnRouteResponseOps
    with ToDeleteCustomerGatewayRequestOps
    with ToDeleteDhcpOptionsRequestOps
    with ToDeleteEgressOnlyInternetGatewayRequestOps
    with ToDeleteEgressOnlyInternetGatewayResponseOps
    with ToDeleteFleetErrorItemOps
    with ToDeleteFleetErrorOps
    with ToDeleteFleetSuccessItemOps
    with ToDeleteFleetsRequestOps
    with ToDeleteFleetsResponseOps
    with ToDeleteFlowLogsRequestOps
    with ToDeleteFlowLogsResponseOps
    with ToDeleteFpgaImageRequestOps
    with ToDeleteFpgaImageResponseOps
    with ToDeleteInternetGatewayRequestOps
    with ToDeleteKeyPairRequestOps
    with ToDeleteLaunchTemplateRequestOps
    with ToDeleteLaunchTemplateResponseOps
    with ToDeleteLaunchTemplateVersionsRequestOps
    with ToDeleteLaunchTemplateVersionsResponseErrorItemOps
    with ToDeleteLaunchTemplateVersionsResponseOps
    with ToDeleteLaunchTemplateVersionsResponseSuccessItemOps
    with ToDeleteLocalGatewayRouteRequestOps
    with ToDeleteLocalGatewayRouteResponseOps
    with ToDeleteLocalGatewayRouteTableVpcAssociationRequestOps
    with ToDeleteLocalGatewayRouteTableVpcAssociationResponseOps
    with ToDeleteNatGatewayRequestOps
    with ToDeleteNatGatewayResponseOps
    with ToDeleteNetworkAclEntryRequestOps
    with ToDeleteNetworkAclRequestOps
    with ToDeleteNetworkInterfacePermissionRequestOps
    with ToDeleteNetworkInterfacePermissionResponseOps
    with ToDeleteNetworkInterfaceRequestOps
    with ToDeletePlacementGroupRequestOps
    with ToDeleteQueuedReservedInstancesErrorOps
    with ToDeleteQueuedReservedInstancesRequestOps
    with ToDeleteQueuedReservedInstancesResponseOps
    with ToDeleteRouteRequestOps
    with ToDeleteRouteTableRequestOps
    with ToDeleteSecurityGroupRequestOps
    with ToDeleteSnapshotRequestOps
    with ToDeleteSubnetRequestOps
    with ToDeleteTagsRequestOps
    with ToDeleteTrafficMirrorFilterRequestOps
    with ToDeleteTrafficMirrorFilterResponseOps
    with ToDeleteTrafficMirrorFilterRuleRequestOps
    with ToDeleteTrafficMirrorFilterRuleResponseOps
    with ToDeleteTrafficMirrorSessionRequestOps
    with ToDeleteTrafficMirrorSessionResponseOps
    with ToDeleteTrafficMirrorTargetRequestOps
    with ToDeleteTrafficMirrorTargetResponseOps
    with ToDeleteTransitGatewayMulticastDomainRequestOps
    with ToDeleteTransitGatewayMulticastDomainResponseOps
    with ToDeleteTransitGatewayPeeringAttachmentRequestOps
    with ToDeleteTransitGatewayPeeringAttachmentResponseOps
    with ToDeleteTransitGatewayRequestOps
    with ToDeleteTransitGatewayResponseOps
    with ToDeleteTransitGatewayRouteRequestOps
    with ToDeleteTransitGatewayRouteResponseOps
    with ToDeleteTransitGatewayRouteTableRequestOps
    with ToDeleteTransitGatewayRouteTableResponseOps
    with ToDeleteTransitGatewayVpcAttachmentRequestOps
    with ToDeleteTransitGatewayVpcAttachmentResponseOps
    with ToDeleteVolumeRequestOps
    with ToDeleteVpcEndpointConnectionNotificationsRequestOps
    with ToDeleteVpcEndpointConnectionNotificationsResponseOps
    with ToDeleteVpcEndpointServiceConfigurationsRequestOps
    with ToDeleteVpcEndpointServiceConfigurationsResponseOps
    with ToDeleteVpcEndpointsRequestOps
    with ToDeleteVpcEndpointsResponseOps
    with ToDeleteVpcPeeringConnectionRequestOps
    with ToDeleteVpcPeeringConnectionResponseOps
    with ToDeleteVpcRequestOps
    with ToDeleteVpnConnectionRequestOps
    with ToDeleteVpnConnectionRouteRequestOps
    with ToDeleteVpnGatewayRequestOps
    with ToDeprovisionByoipCidrRequestOps
    with ToDeprovisionByoipCidrResponseOps
    with ToDeregisterImageRequestOps
    with ToDeregisterTransitGatewayMulticastGroupMembersRequestOps
    with ToDeregisterTransitGatewayMulticastGroupMembersResponseOps
    with ToDeregisterTransitGatewayMulticastGroupSourcesRequestOps
    with ToDeregisterTransitGatewayMulticastGroupSourcesResponseOps
    with ToDescribeAccountAttributesRequestOps
    with ToDescribeAccountAttributesResponseOps
    with ToDescribeAddressesRequestOps
    with ToDescribeAddressesResponseOps
    with ToDescribeAggregateIdFormatResponseOps
    with ToDescribeAvailabilityZonesRequestOps
    with ToDescribeAvailabilityZonesResponseOps
    with ToDescribeBundleTasksRequestOps
    with ToDescribeBundleTasksResponseOps
    with ToDescribeByoipCidrsRequestOps
    with ToDescribeByoipCidrsResponseOps
    with ToDescribeCapacityReservationsRequestOps
    with ToDescribeCapacityReservationsResponseOps
    with ToDescribeClassicLinkInstancesRequestOps
    with ToDescribeClassicLinkInstancesResponseOps
    with ToDescribeClientVpnAuthorizationRulesRequestOps
    with ToDescribeClientVpnAuthorizationRulesResponseOps
    with ToDescribeClientVpnConnectionsRequestOps
    with ToDescribeClientVpnConnectionsResponseOps
    with ToDescribeClientVpnEndpointsRequestOps
    with ToDescribeClientVpnEndpointsResponseOps
    with ToDescribeClientVpnRoutesRequestOps
    with ToDescribeClientVpnRoutesResponseOps
    with ToDescribeClientVpnTargetNetworksRequestOps
    with ToDescribeClientVpnTargetNetworksResponseOps
    with ToDescribeCoipPoolsRequestOps
    with ToDescribeCoipPoolsResponseOps
    with ToDescribeConversionTasksRequestOps
    with ToDescribeConversionTasksResponseOps
    with ToDescribeCustomerGatewaysRequestOps
    with ToDescribeCustomerGatewaysResponseOps
    with ToDescribeDhcpOptionsRequestOps
    with ToDescribeDhcpOptionsResponseOps
    with ToDescribeEgressOnlyInternetGatewaysRequestOps
    with ToDescribeEgressOnlyInternetGatewaysResponseOps
    with ToDescribeElasticGpusRequestOps
    with ToDescribeElasticGpusResponseOps
    with ToDescribeExportImageTasksRequestOps
    with ToDescribeExportImageTasksResponseOps
    with ToDescribeExportTasksRequestOps
    with ToDescribeExportTasksResponseOps
    with ToDescribeFastSnapshotRestoreSuccessItemOps
    with ToDescribeFastSnapshotRestoresRequestOps
    with ToDescribeFastSnapshotRestoresResponseOps
    with ToDescribeFleetErrorOps
    with ToDescribeFleetHistoryRequestOps
    with ToDescribeFleetHistoryResponseOps
    with ToDescribeFleetInstancesRequestOps
    with ToDescribeFleetInstancesResponseOps
    with ToDescribeFleetsInstancesOps
    with ToDescribeFleetsRequestOps
    with ToDescribeFleetsResponseOps
    with ToDescribeFlowLogsRequestOps
    with ToDescribeFlowLogsResponseOps
    with ToDescribeFpgaImageAttributeRequestOps
    with ToDescribeFpgaImageAttributeResponseOps
    with ToDescribeFpgaImagesRequestOps
    with ToDescribeFpgaImagesResponseOps
    with ToDescribeHostReservationOfferingsRequestOps
    with ToDescribeHostReservationOfferingsResponseOps
    with ToDescribeHostReservationsRequestOps
    with ToDescribeHostReservationsResponseOps
    with ToDescribeHostsRequestOps
    with ToDescribeHostsResponseOps
    with ToDescribeIamInstanceProfileAssociationsRequestOps
    with ToDescribeIamInstanceProfileAssociationsResponseOps
    with ToDescribeIdFormatRequestOps
    with ToDescribeIdFormatResponseOps
    with ToDescribeIdentityIdFormatRequestOps
    with ToDescribeIdentityIdFormatResponseOps
    with ToDescribeImageAttributeRequestOps
    with ToDescribeImageAttributeResponseOps
    with ToDescribeImagesRequestOps
    with ToDescribeImagesResponseOps
    with ToDescribeImportImageTasksRequestOps
    with ToDescribeImportImageTasksResponseOps
    with ToDescribeImportSnapshotTasksRequestOps
    with ToDescribeImportSnapshotTasksResponseOps
    with ToDescribeInstanceAttributeRequestOps
    with ToDescribeInstanceAttributeResponseOps
    with ToDescribeInstanceCreditSpecificationsRequestOps
    with ToDescribeInstanceCreditSpecificationsResponseOps
    with ToDescribeInstanceStatusRequestOps
    with ToDescribeInstanceStatusResponseOps
    with ToDescribeInstanceTypeOfferingsRequestOps
    with ToDescribeInstanceTypeOfferingsResponseOps
    with ToDescribeInstanceTypesRequestOps
    with ToDescribeInstanceTypesResponseOps
    with ToDescribeInstancesRequestOps
    with ToDescribeInstancesResponseOps
    with ToDescribeInternetGatewaysRequestOps
    with ToDescribeInternetGatewaysResponseOps
    with ToDescribeIpv6PoolsRequestOps
    with ToDescribeIpv6PoolsResponseOps
    with ToDescribeKeyPairsRequestOps
    with ToDescribeKeyPairsResponseOps
    with ToDescribeLaunchTemplateVersionsRequestOps
    with ToDescribeLaunchTemplateVersionsResponseOps
    with ToDescribeLaunchTemplatesRequestOps
    with ToDescribeLaunchTemplatesResponseOps
    with ToDescribeLocalGatewayRouteTableVirtualInterfaceGroupAssociationsRequestOps
    with ToDescribeLocalGatewayRouteTableVirtualInterfaceGroupAssociationsResponseOps
    with ToDescribeLocalGatewayRouteTableVpcAssociationsRequestOps
    with ToDescribeLocalGatewayRouteTableVpcAssociationsResponseOps
    with ToDescribeLocalGatewayRouteTablesRequestOps
    with ToDescribeLocalGatewayRouteTablesResponseOps
    with ToDescribeLocalGatewayVirtualInterfaceGroupsRequestOps
    with ToDescribeLocalGatewayVirtualInterfaceGroupsResponseOps
    with ToDescribeLocalGatewayVirtualInterfacesRequestOps
    with ToDescribeLocalGatewayVirtualInterfacesResponseOps
    with ToDescribeLocalGatewaysRequestOps
    with ToDescribeLocalGatewaysResponseOps
    with ToDescribeMovingAddressesRequestOps
    with ToDescribeMovingAddressesResponseOps
    with ToDescribeNatGatewaysRequestOps
    with ToDescribeNatGatewaysResponseOps
    with ToDescribeNetworkAclsRequestOps
    with ToDescribeNetworkAclsResponseOps
    with ToDescribeNetworkInterfaceAttributeRequestOps
    with ToDescribeNetworkInterfaceAttributeResponseOps
    with ToDescribeNetworkInterfacePermissionsRequestOps
    with ToDescribeNetworkInterfacePermissionsResponseOps
    with ToDescribeNetworkInterfacesRequestOps
    with ToDescribeNetworkInterfacesResponseOps
    with ToDescribePlacementGroupsRequestOps
    with ToDescribePlacementGroupsResponseOps
    with ToDescribePrefixListsRequestOps
    with ToDescribePrefixListsResponseOps
    with ToDescribePrincipalIdFormatRequestOps
    with ToDescribePrincipalIdFormatResponseOps
    with ToDescribePublicIpv4PoolsRequestOps
    with ToDescribePublicIpv4PoolsResponseOps
    with ToDescribeRegionsRequestOps
    with ToDescribeRegionsResponseOps
    with ToDescribeReservedInstancesListingsRequestOps
    with ToDescribeReservedInstancesListingsResponseOps
    with ToDescribeReservedInstancesModificationsRequestOps
    with ToDescribeReservedInstancesModificationsResponseOps
    with ToDescribeReservedInstancesOfferingsRequestOps
    with ToDescribeReservedInstancesOfferingsResponseOps
    with ToDescribeReservedInstancesRequestOps
    with ToDescribeReservedInstancesResponseOps
    with ToDescribeRouteTablesRequestOps
    with ToDescribeRouteTablesResponseOps
    with ToDescribeScheduledInstanceAvailabilityRequestOps
    with ToDescribeScheduledInstanceAvailabilityResponseOps
    with ToDescribeScheduledInstancesRequestOps
    with ToDescribeScheduledInstancesResponseOps
    with ToDescribeSecurityGroupReferencesRequestOps
    with ToDescribeSecurityGroupReferencesResponseOps
    with ToDescribeSecurityGroupsRequestOps
    with ToDescribeSecurityGroupsResponseOps
    with ToDescribeSnapshotAttributeRequestOps
    with ToDescribeSnapshotAttributeResponseOps
    with ToDescribeSnapshotsRequestOps
    with ToDescribeSnapshotsResponseOps
    with ToDescribeSpotDatafeedSubscriptionResponseOps
    with ToDescribeSpotFleetInstancesRequestOps
    with ToDescribeSpotFleetInstancesResponseOps
    with ToDescribeSpotFleetRequestHistoryRequestOps
    with ToDescribeSpotFleetRequestHistoryResponseOps
    with ToDescribeSpotFleetRequestsRequestOps
    with ToDescribeSpotFleetRequestsResponseOps
    with ToDescribeSpotInstanceRequestsRequestOps
    with ToDescribeSpotInstanceRequestsResponseOps
    with ToDescribeSpotPriceHistoryRequestOps
    with ToDescribeSpotPriceHistoryResponseOps
    with ToDescribeStaleSecurityGroupsRequestOps
    with ToDescribeStaleSecurityGroupsResponseOps
    with ToDescribeSubnetsRequestOps
    with ToDescribeSubnetsResponseOps
    with ToDescribeTagsRequestOps
    with ToDescribeTagsResponseOps
    with ToDescribeTrafficMirrorFiltersRequestOps
    with ToDescribeTrafficMirrorFiltersResponseOps
    with ToDescribeTrafficMirrorSessionsRequestOps
    with ToDescribeTrafficMirrorSessionsResponseOps
    with ToDescribeTrafficMirrorTargetsRequestOps
    with ToDescribeTrafficMirrorTargetsResponseOps
    with ToDescribeTransitGatewayAttachmentsRequestOps
    with ToDescribeTransitGatewayAttachmentsResponseOps
    with ToDescribeTransitGatewayMulticastDomainsRequestOps
    with ToDescribeTransitGatewayMulticastDomainsResponseOps
    with ToDescribeTransitGatewayPeeringAttachmentsRequestOps
    with ToDescribeTransitGatewayPeeringAttachmentsResponseOps
    with ToDescribeTransitGatewayRouteTablesRequestOps
    with ToDescribeTransitGatewayRouteTablesResponseOps
    with ToDescribeTransitGatewayVpcAttachmentsRequestOps
    with ToDescribeTransitGatewayVpcAttachmentsResponseOps
    with ToDescribeTransitGatewaysRequestOps
    with ToDescribeTransitGatewaysResponseOps
    with ToDescribeVolumeAttributeRequestOps
    with ToDescribeVolumeAttributeResponseOps
    with ToDescribeVolumeStatusRequestOps
    with ToDescribeVolumeStatusResponseOps
    with ToDescribeVolumesModificationsRequestOps
    with ToDescribeVolumesModificationsResponseOps
    with ToDescribeVolumesRequestOps
    with ToDescribeVolumesResponseOps
    with ToDescribeVpcAttributeRequestOps
    with ToDescribeVpcAttributeResponseOps
    with ToDescribeVpcClassicLinkDnsSupportRequestOps
    with ToDescribeVpcClassicLinkDnsSupportResponseOps
    with ToDescribeVpcClassicLinkRequestOps
    with ToDescribeVpcClassicLinkResponseOps
    with ToDescribeVpcEndpointConnectionNotificationsRequestOps
    with ToDescribeVpcEndpointConnectionNotificationsResponseOps
    with ToDescribeVpcEndpointConnectionsRequestOps
    with ToDescribeVpcEndpointConnectionsResponseOps
    with ToDescribeVpcEndpointServiceConfigurationsRequestOps
    with ToDescribeVpcEndpointServiceConfigurationsResponseOps
    with ToDescribeVpcEndpointServicePermissionsRequestOps
    with ToDescribeVpcEndpointServicePermissionsResponseOps
    with ToDescribeVpcEndpointServicesRequestOps
    with ToDescribeVpcEndpointServicesResponseOps
    with ToDescribeVpcEndpointsRequestOps
    with ToDescribeVpcEndpointsResponseOps
    with ToDescribeVpcPeeringConnectionsRequestOps
    with ToDescribeVpcPeeringConnectionsResponseOps
    with ToDescribeVpcsRequestOps
    with ToDescribeVpcsResponseOps
    with ToDescribeVpnConnectionsRequestOps
    with ToDescribeVpnConnectionsResponseOps
    with ToDescribeVpnGatewaysRequestOps
    with ToDescribeVpnGatewaysResponseOps
    with ToDetachClassicLinkVpcRequestOps
    with ToDetachClassicLinkVpcResponseOps
    with ToDetachInternetGatewayRequestOps
    with ToDetachNetworkInterfaceRequestOps
    with ToDetachVolumeRequestOps
    with ToDetachVolumeResponseOps
    with ToDetachVpnGatewayRequestOps
    with ToDhcpConfigurationOps
    with ToDhcpOptionsOps
    with ToDirectoryServiceAuthenticationOps
    with ToDirectoryServiceAuthenticationRequestOps
    with ToDisableEbsEncryptionByDefaultResponseOps
    with ToDisableFastSnapshotRestoreErrorItemOps
    with ToDisableFastSnapshotRestoreStateErrorItemOps
    with ToDisableFastSnapshotRestoreStateErrorOps
    with ToDisableFastSnapshotRestoreSuccessItemOps
    with ToDisableFastSnapshotRestoresRequestOps
    with ToDisableFastSnapshotRestoresResponseOps
    with ToDisableTransitGatewayRouteTablePropagationRequestOps
    with ToDisableTransitGatewayRouteTablePropagationResponseOps
    with ToDisableVgwRoutePropagationRequestOps
    with ToDisableVpcClassicLinkDnsSupportRequestOps
    with ToDisableVpcClassicLinkDnsSupportResponseOps
    with ToDisableVpcClassicLinkRequestOps
    with ToDisableVpcClassicLinkResponseOps
    with ToDisassociateAddressRequestOps
    with ToDisassociateClientVpnTargetNetworkRequestOps
    with ToDisassociateClientVpnTargetNetworkResponseOps
    with ToDisassociateIamInstanceProfileRequestOps
    with ToDisassociateIamInstanceProfileResponseOps
    with ToDisassociateRouteTableRequestOps
    with ToDisassociateSubnetCidrBlockRequestOps
    with ToDisassociateSubnetCidrBlockResponseOps
    with ToDisassociateTransitGatewayMulticastDomainRequestOps
    with ToDisassociateTransitGatewayMulticastDomainResponseOps
    with ToDisassociateTransitGatewayRouteTableRequestOps
    with ToDisassociateTransitGatewayRouteTableResponseOps
    with ToDisassociateVpcCidrBlockRequestOps
    with ToDisassociateVpcCidrBlockResponseOps
    with ToDiskImageDescriptionOps
    with ToDiskImageDetailOps
    with ToDiskImageOps
    with ToDiskImageVolumeDescriptionOps
    with ToDiskInfoOps
    with ToDnsEntryOps
    with ToDnsServersOptionsModifyStructureOps
    with ToEbsBlockDeviceOps
    with ToEbsInfoOps
    with ToEbsInstanceBlockDeviceOps
    with ToEbsInstanceBlockDeviceSpecificationOps
    with ToEgressOnlyInternetGatewayOps
    with ToElasticGpuAssociationOps
    with ToElasticGpuHealthOps
    with ToElasticGpuSpecificationOps
    with ToElasticGpuSpecificationResponseOps
    with ToElasticGpusOps
    with ToElasticInferenceAcceleratorAssociationOps
    with ToElasticInferenceAcceleratorOps
    with ToEnableEbsEncryptionByDefaultResponseOps
    with ToEnableFastSnapshotRestoreErrorItemOps
    with ToEnableFastSnapshotRestoreStateErrorItemOps
    with ToEnableFastSnapshotRestoreStateErrorOps
    with ToEnableFastSnapshotRestoreSuccessItemOps
    with ToEnableFastSnapshotRestoresRequestOps
    with ToEnableFastSnapshotRestoresResponseOps
    with ToEnableTransitGatewayRouteTablePropagationRequestOps
    with ToEnableTransitGatewayRouteTablePropagationResponseOps
    with ToEnableVgwRoutePropagationRequestOps
    with ToEnableVolumeIoRequestOps
    with ToEnableVpcClassicLinkDnsSupportRequestOps
    with ToEnableVpcClassicLinkDnsSupportResponseOps
    with ToEnableVpcClassicLinkRequestOps
    with ToEnableVpcClassicLinkResponseOps
    with ToEventInformationOps
    with ToExportClientVpnClientCertificateRevocationListRequestOps
    with ToExportClientVpnClientCertificateRevocationListResponseOps
    with ToExportClientVpnClientConfigurationRequestOps
    with ToExportClientVpnClientConfigurationResponseOps
    with ToExportImageRequestOps
    with ToExportImageResponseOps
    with ToExportImageTaskOps
    with ToExportTaskOps
    with ToExportTaskS3LocationOps
    with ToExportTaskS3LocationRequestOps
    with ToExportToS3TaskOps
    with ToExportToS3TaskSpecificationOps
    with ToExportTransitGatewayRoutesRequestOps
    with ToExportTransitGatewayRoutesResponseOps
    with ToFailedQueuedPurchaseDeletionOps
    with ToFilterOps
    with ToFleetDataOps
    with ToFleetLaunchTemplateConfigOps
    with ToFleetLaunchTemplateConfigRequestOps
    with ToFleetLaunchTemplateOverridesOps
    with ToFleetLaunchTemplateOverridesRequestOps
    with ToFleetLaunchTemplateSpecificationOps
    with ToFleetLaunchTemplateSpecificationRequestOps
    with ToFlowLogOps
    with ToFpgaDeviceInfoOps
    with ToFpgaDeviceMemoryInfoOps
    with ToFpgaImageAttributeOps
    with ToFpgaImageOps
    with ToFpgaImageStateOps
    with ToFpgaInfoOps
    with ToGetAssociatedIpv6PoolCidrsRequestOps
    with ToGetAssociatedIpv6PoolCidrsResponseOps
    with ToGetCapacityReservationUsageRequestOps
    with ToGetCapacityReservationUsageResponseOps
    with ToGetCoipPoolUsageRequestOps
    with ToGetCoipPoolUsageResponseOps
    with ToGetConsoleOutputRequestOps
    with ToGetConsoleOutputResponseOps
    with ToGetConsoleScreenshotRequestOps
    with ToGetConsoleScreenshotResponseOps
    with ToGetDefaultCreditSpecificationRequestOps
    with ToGetDefaultCreditSpecificationResponseOps
    with ToGetEbsDefaultKmsKeyIdResponseOps
    with ToGetEbsEncryptionByDefaultResponseOps
    with ToGetHostReservationPurchasePreviewRequestOps
    with ToGetHostReservationPurchasePreviewResponseOps
    with ToGetLaunchTemplateDataRequestOps
    with ToGetLaunchTemplateDataResponseOps
    with ToGetPasswordDataRequestOps
    with ToGetPasswordDataResponseOps
    with ToGetReservedInstancesExchangeQuoteRequestOps
    with ToGetReservedInstancesExchangeQuoteResponseOps
    with ToGetTransitGatewayAttachmentPropagationsRequestOps
    with ToGetTransitGatewayAttachmentPropagationsResponseOps
    with ToGetTransitGatewayMulticastDomainAssociationsRequestOps
    with ToGetTransitGatewayMulticastDomainAssociationsResponseOps
    with ToGetTransitGatewayRouteTableAssociationsRequestOps
    with ToGetTransitGatewayRouteTableAssociationsResponseOps
    with ToGetTransitGatewayRouteTablePropagationsRequestOps
    with ToGetTransitGatewayRouteTablePropagationsResponseOps
    with ToGpuDeviceInfoOps
    with ToGpuDeviceMemoryInfoOps
    with ToGpuInfoOps
    with ToGroupIdentifierOps
    with ToHibernationOptionsOps
    with ToHibernationOptionsRequestOps
    with ToHistoryRecordEntryOps
    with ToHistoryRecordOps
    with ToHostInstanceOps
    with ToHostOfferingOps
    with ToHostOps
    with ToHostPropertiesOps
    with ToHostReservationOps
    with ToIKEVersionsListValueOps
    with ToIKEVersionsRequestListValueOps
    with ToIamInstanceProfileAssociationOps
    with ToIamInstanceProfileOps
    with ToIamInstanceProfileSpecificationOps
    with ToIcmpTypeCodeOps
    with ToIdFormatOps
    with ToImageDiskContainerOps
    with ToImageOps
    with ToImportClientVpnClientCertificateRevocationListRequestOps
    with ToImportClientVpnClientCertificateRevocationListResponseOps
    with ToImportImageLicenseConfigurationRequestOps
    with ToImportImageLicenseConfigurationResponseOps
    with ToImportImageRequestOps
    with ToImportImageResponseOps
    with ToImportImageTaskOps
    with ToImportInstanceLaunchSpecificationOps
    with ToImportInstanceRequestOps
    with ToImportInstanceResponseOps
    with ToImportInstanceTaskDetailsOps
    with ToImportInstanceVolumeDetailItemOps
    with ToImportKeyPairRequestOps
    with ToImportKeyPairResponseOps
    with ToImportSnapshotRequestOps
    with ToImportSnapshotResponseOps
    with ToImportSnapshotTaskOps
    with ToImportVolumeRequestOps
    with ToImportVolumeResponseOps
    with ToImportVolumeTaskDetailsOps
    with ToInferenceAcceleratorInfoOps
    with ToInferenceDeviceInfoOps
    with ToInstanceBlockDeviceMappingOps
    with ToInstanceBlockDeviceMappingSpecificationOps
    with ToInstanceCapacityOps
    with ToInstanceCountOps
    with ToInstanceCreditSpecificationOps
    with ToInstanceCreditSpecificationRequestOps
    with ToInstanceExportDetailsOps
    with ToInstanceFamilyCreditSpecificationOps
    with ToInstanceIpv6AddressOps
    with ToInstanceIpv6AddressRequestOps
    with ToInstanceMarketOptionsRequestOps
    with ToInstanceMetadataOptionsRequestOps
    with ToInstanceMetadataOptionsResponseOps
    with ToInstanceMonitoringOps
    with ToInstanceNetworkInterfaceAssociationOps
    with ToInstanceNetworkInterfaceAttachmentOps
    with ToInstanceNetworkInterfaceOps
    with ToInstanceNetworkInterfaceSpecificationOps
    with ToInstanceOps
    with ToInstancePrivateIpAddressOps
    with ToInstanceSpecificationOps
    with ToInstanceStateChangeOps
    with ToInstanceStateOps
    with ToInstanceStatusDetailsOps
    with ToInstanceStatusEventOps
    with ToInstanceStatusOps
    with ToInstanceStatusSummaryOps
    with ToInstanceStorageInfoOps
    with ToInstanceTypeInfoOps
    with ToInstanceTypeOfferingOps
    with ToInstanceUsageOps
    with ToInternetGatewayAttachmentOps
    with ToInternetGatewayOps
    with ToIpPermissionOps
    with ToIpRangeOps
    with ToIpv6CidrAssociationOps
    with ToIpv6CidrBlockOps
    with ToIpv6PoolOps
    with ToIpv6RangeOps
    with ToKeyPairInfoOps
    with ToLastErrorOps
    with ToLaunchPermissionModificationsOps
    with ToLaunchPermissionOps
    with ToLaunchSpecificationOps
    with ToLaunchTemplateAndOverridesResponseOps
    with ToLaunchTemplateBlockDeviceMappingOps
    with ToLaunchTemplateBlockDeviceMappingRequestOps
    with ToLaunchTemplateCapacityReservationSpecificationRequestOps
    with ToLaunchTemplateCapacityReservationSpecificationResponseOps
    with ToLaunchTemplateConfigOps
    with ToLaunchTemplateCpuOptionsOps
    with ToLaunchTemplateCpuOptionsRequestOps
    with ToLaunchTemplateEbsBlockDeviceOps
    with ToLaunchTemplateEbsBlockDeviceRequestOps
    with ToLaunchTemplateElasticInferenceAcceleratorOps
    with ToLaunchTemplateElasticInferenceAcceleratorResponseOps
    with ToLaunchTemplateHibernationOptionsOps
    with ToLaunchTemplateHibernationOptionsRequestOps
    with ToLaunchTemplateIamInstanceProfileSpecificationOps
    with ToLaunchTemplateIamInstanceProfileSpecificationRequestOps
    with ToLaunchTemplateInstanceMarketOptionsOps
    with ToLaunchTemplateInstanceMarketOptionsRequestOps
    with ToLaunchTemplateInstanceMetadataOptionsOps
    with ToLaunchTemplateInstanceMetadataOptionsRequestOps
    with ToLaunchTemplateInstanceNetworkInterfaceSpecificationOps
    with ToLaunchTemplateInstanceNetworkInterfaceSpecificationRequestOps
    with ToLaunchTemplateLicenseConfigurationOps
    with ToLaunchTemplateLicenseConfigurationRequestOps
    with ToLaunchTemplateOps
    with ToLaunchTemplateOverridesOps
    with ToLaunchTemplatePlacementOps
    with ToLaunchTemplatePlacementRequestOps
    with ToLaunchTemplateSpecificationOps
    with ToLaunchTemplateSpotMarketOptionsOps
    with ToLaunchTemplateSpotMarketOptionsRequestOps
    with ToLaunchTemplateTagSpecificationOps
    with ToLaunchTemplateTagSpecificationRequestOps
    with ToLaunchTemplateVersionOps
    with ToLaunchTemplatesMonitoringOps
    with ToLaunchTemplatesMonitoringRequestOps
    with ToLicenseConfigurationOps
    with ToLicenseConfigurationRequestOps
    with ToLoadBalancersConfigOps
    with ToLoadPermissionModificationsOps
    with ToLoadPermissionOps
    with ToLoadPermissionRequestOps
    with ToLocalGatewayOps
    with ToLocalGatewayRouteOps
    with ToLocalGatewayRouteTableOps
    with ToLocalGatewayRouteTableVirtualInterfaceGroupAssociationOps
    with ToLocalGatewayRouteTableVpcAssociationOps
    with ToLocalGatewayVirtualInterfaceGroupOps
    with ToLocalGatewayVirtualInterfaceOps
    with ToMemoryInfoOps
    with ToModifyAvailabilityZoneGroupRequestOps
    with ToModifyAvailabilityZoneGroupResponseOps
    with ToModifyCapacityReservationRequestOps
    with ToModifyCapacityReservationResponseOps
    with ToModifyClientVpnEndpointRequestOps
    with ToModifyClientVpnEndpointResponseOps
    with ToModifyDefaultCreditSpecificationRequestOps
    with ToModifyDefaultCreditSpecificationResponseOps
    with ToModifyEbsDefaultKmsKeyIdRequestOps
    with ToModifyEbsDefaultKmsKeyIdResponseOps
    with ToModifyFleetRequestOps
    with ToModifyFleetResponseOps
    with ToModifyFpgaImageAttributeRequestOps
    with ToModifyFpgaImageAttributeResponseOps
    with ToModifyHostsRequestOps
    with ToModifyHostsResponseOps
    with ToModifyIdFormatRequestOps
    with ToModifyIdentityIdFormatRequestOps
    with ToModifyImageAttributeRequestOps
    with ToModifyInstanceAttributeRequestOps
    with ToModifyInstanceCapacityReservationAttributesRequestOps
    with ToModifyInstanceCapacityReservationAttributesResponseOps
    with ToModifyInstanceCreditSpecificationRequestOps
    with ToModifyInstanceCreditSpecificationResponseOps
    with ToModifyInstanceEventStartTimeRequestOps
    with ToModifyInstanceEventStartTimeResponseOps
    with ToModifyInstanceMetadataOptionsRequestOps
    with ToModifyInstanceMetadataOptionsResponseOps
    with ToModifyInstancePlacementRequestOps
    with ToModifyInstancePlacementResponseOps
    with ToModifyLaunchTemplateRequestOps
    with ToModifyLaunchTemplateResponseOps
    with ToModifyNetworkInterfaceAttributeRequestOps
    with ToModifyReservedInstancesRequestOps
    with ToModifyReservedInstancesResponseOps
    with ToModifySnapshotAttributeRequestOps
    with ToModifySpotFleetRequestRequestOps
    with ToModifySpotFleetRequestResponseOps
    with ToModifySubnetAttributeRequestOps
    with ToModifyTrafficMirrorFilterNetworkServicesRequestOps
    with ToModifyTrafficMirrorFilterNetworkServicesResponseOps
    with ToModifyTrafficMirrorFilterRuleRequestOps
    with ToModifyTrafficMirrorFilterRuleResponseOps
    with ToModifyTrafficMirrorSessionRequestOps
    with ToModifyTrafficMirrorSessionResponseOps
    with ToModifyTransitGatewayVpcAttachmentRequestOps
    with ToModifyTransitGatewayVpcAttachmentRequestOptionsOps
    with ToModifyTransitGatewayVpcAttachmentResponseOps
    with ToModifyVolumeAttributeRequestOps
    with ToModifyVolumeRequestOps
    with ToModifyVolumeResponseOps
    with ToModifyVpcAttributeRequestOps
    with ToModifyVpcEndpointConnectionNotificationRequestOps
    with ToModifyVpcEndpointConnectionNotificationResponseOps
    with ToModifyVpcEndpointRequestOps
    with ToModifyVpcEndpointResponseOps
    with ToModifyVpcEndpointServiceConfigurationRequestOps
    with ToModifyVpcEndpointServiceConfigurationResponseOps
    with ToModifyVpcEndpointServicePermissionsRequestOps
    with ToModifyVpcEndpointServicePermissionsResponseOps
    with ToModifyVpcPeeringConnectionOptionsRequestOps
    with ToModifyVpcPeeringConnectionOptionsResponseOps
    with ToModifyVpcTenancyRequestOps
    with ToModifyVpcTenancyResponseOps
    with ToModifyVpnConnectionRequestOps
    with ToModifyVpnConnectionResponseOps
    with ToModifyVpnTunnelCertificateRequestOps
    with ToModifyVpnTunnelCertificateResponseOps
    with ToModifyVpnTunnelOptionsRequestOps
    with ToModifyVpnTunnelOptionsResponseOps
    with ToModifyVpnTunnelOptionsSpecificationOps
    with ToMonitorInstancesRequestOps
    with ToMonitorInstancesResponseOps
    with ToMonitoringOps
    with ToMoveAddressToVpcRequestOps
    with ToMoveAddressToVpcResponseOps
    with ToMovingAddressStatusOps
    with ToNatGatewayAddressOps
    with ToNatGatewayOps
    with ToNetworkAclAssociationOps
    with ToNetworkAclEntryOps
    with ToNetworkAclOps
    with ToNetworkInfoOps
    with ToNetworkInterfaceAssociationOps
    with ToNetworkInterfaceAttachmentChangesOps
    with ToNetworkInterfaceAttachmentOps
    with ToNetworkInterfaceIpv6AddressOps
    with ToNetworkInterfaceOps
    with ToNetworkInterfacePermissionOps
    with ToNetworkInterfacePermissionStateOps
    with ToNetworkInterfacePrivateIpAddressOps
    with ToNewDhcpConfigurationOps
    with ToOnDemandOptionsOps
    with ToOnDemandOptionsRequestOps
    with ToPciIdOps
    with ToPeeringAttachmentStatusOps
    with ToPeeringConnectionOptionsOps
    with ToPeeringConnectionOptionsRequestOps
    with ToPeeringTgwInfoOps
    with ToPhase1DHGroupNumbersListValueOps
    with ToPhase1DHGroupNumbersRequestListValueOps
    with ToPhase1EncryptionAlgorithmsListValueOps
    with ToPhase1EncryptionAlgorithmsRequestListValueOps
    with ToPhase1IntegrityAlgorithmsListValueOps
    with ToPhase1IntegrityAlgorithmsRequestListValueOps
    with ToPhase2DHGroupNumbersListValueOps
    with ToPhase2DHGroupNumbersRequestListValueOps
    with ToPhase2EncryptionAlgorithmsListValueOps
    with ToPhase2EncryptionAlgorithmsRequestListValueOps
    with ToPhase2IntegrityAlgorithmsListValueOps
    with ToPhase2IntegrityAlgorithmsRequestListValueOps
    with ToPlacementGroupInfoOps
    with ToPlacementGroupOps
    with ToPlacementOps
    with ToPlacementResponseOps
    with ToPoolCidrBlockOps
    with ToPortRangeOps
    with ToPrefixListIdOps
    with ToPrefixListOps
    with ToPriceScheduleOps
    with ToPriceScheduleSpecificationOps
    with ToPricingDetailOps
    with ToPrincipalIdFormatOps
    with ToPrivateDnsNameConfigurationOps
    with ToPrivateIpAddressSpecificationOps
    with ToProcessorInfoOps
    with ToProductCodeOps
    with ToPropagatingVgwOps
    with ToProvisionByoipCidrRequestOps
    with ToProvisionByoipCidrResponseOps
    with ToProvisionedBandwidthOps
    with ToPublicIpv4PoolOps
    with ToPublicIpv4PoolRangeOps
    with ToPurchaseHostReservationRequestOps
    with ToPurchaseHostReservationResponseOps
    with ToPurchaseOps
    with ToPurchaseRequestOps
    with ToPurchaseReservedInstancesOfferingRequestOps
    with ToPurchaseReservedInstancesOfferingResponseOps
    with ToPurchaseScheduledInstancesRequestOps
    with ToPurchaseScheduledInstancesResponseOps
    with ToRebootInstancesRequestOps
    with ToRecurringChargeOps
    with ToRegionOps
    with ToRegisterImageRequestOps
    with ToRegisterImageResponseOps
    with ToRegisterTransitGatewayMulticastGroupMembersRequestOps
    with ToRegisterTransitGatewayMulticastGroupMembersResponseOps
    with ToRegisterTransitGatewayMulticastGroupSourcesRequestOps
    with ToRegisterTransitGatewayMulticastGroupSourcesResponseOps
    with ToRejectTransitGatewayPeeringAttachmentRequestOps
    with ToRejectTransitGatewayPeeringAttachmentResponseOps
    with ToRejectTransitGatewayVpcAttachmentRequestOps
    with ToRejectTransitGatewayVpcAttachmentResponseOps
    with ToRejectVpcEndpointConnectionsRequestOps
    with ToRejectVpcEndpointConnectionsResponseOps
    with ToRejectVpcPeeringConnectionRequestOps
    with ToRejectVpcPeeringConnectionResponseOps
    with ToReleaseAddressRequestOps
    with ToReleaseHostsRequestOps
    with ToReleaseHostsResponseOps
    with ToReplaceIamInstanceProfileAssociationRequestOps
    with ToReplaceIamInstanceProfileAssociationResponseOps
    with ToReplaceNetworkAclAssociationRequestOps
    with ToReplaceNetworkAclAssociationResponseOps
    with ToReplaceNetworkAclEntryRequestOps
    with ToReplaceRouteRequestOps
    with ToReplaceRouteTableAssociationRequestOps
    with ToReplaceRouteTableAssociationResponseOps
    with ToReplaceTransitGatewayRouteRequestOps
    with ToReplaceTransitGatewayRouteResponseOps
    with ToReportInstanceStatusRequestOps
    with ToRequestLaunchTemplateDataOps
    with ToRequestSpotFleetRequestOps
    with ToRequestSpotFleetResponseOps
    with ToRequestSpotInstancesRequestOps
    with ToRequestSpotInstancesResponseOps
    with ToRequestSpotLaunchSpecificationOps
    with ToReservationOps
    with ToReservationValueOps
    with ToReservedInstanceLimitPriceOps
    with ToReservedInstanceReservationValueOps
    with ToReservedInstancesConfigurationOps
    with ToReservedInstancesIdOps
    with ToReservedInstancesListingOps
    with ToReservedInstancesModificationOps
    with ToReservedInstancesModificationResultOps
    with ToReservedInstancesOfferingOps
    with ToReservedInstancesOps
    with ToResetEbsDefaultKmsKeyIdResponseOps
    with ToResetFpgaImageAttributeRequestOps
    with ToResetFpgaImageAttributeResponseOps
    with ToResetImageAttributeRequestOps
    with ToResetInstanceAttributeRequestOps
    with ToResetNetworkInterfaceAttributeRequestOps
    with ToResetSnapshotAttributeRequestOps
    with ToResponseErrorOps
    with ToResponseLaunchTemplateDataOps
    with ToRestoreAddressToClassicRequestOps
    with ToRestoreAddressToClassicResponseOps
    with ToRevokeClientVpnIngressRequestOps
    with ToRevokeClientVpnIngressResponseOps
    with ToRevokeSecurityGroupEgressRequestOps
    with ToRevokeSecurityGroupIngressRequestOps
    with ToRouteOps
    with ToRouteTableAssociationOps
    with ToRouteTableAssociationStateOps
    with ToRouteTableOps
    with ToRunInstancesMonitoringEnabledOps
    with ToRunInstancesRequestOps
    with ToRunInstancesResponseOps
    with ToRunScheduledInstancesRequestOps
    with ToRunScheduledInstancesResponseOps
    with ToS3StorageOps
    with ToScheduledInstanceAvailabilityOps
    with ToScheduledInstanceOps
    with ToScheduledInstanceRecurrenceOps
    with ToScheduledInstanceRecurrenceRequestOps
    with ToScheduledInstancesBlockDeviceMappingOps
    with ToScheduledInstancesEbsOps
    with ToScheduledInstancesIamInstanceProfileOps
    with ToScheduledInstancesIpv6AddressOps
    with ToScheduledInstancesLaunchSpecificationOps
    with ToScheduledInstancesMonitoringOps
    with ToScheduledInstancesNetworkInterfaceOps
    with ToScheduledInstancesPlacementOps
    with ToScheduledInstancesPrivateIpAddressConfigOps
    with ToSearchLocalGatewayRoutesRequestOps
    with ToSearchLocalGatewayRoutesResponseOps
    with ToSearchTransitGatewayMulticastGroupsRequestOps
    with ToSearchTransitGatewayMulticastGroupsResponseOps
    with ToSearchTransitGatewayRoutesRequestOps
    with ToSearchTransitGatewayRoutesResponseOps
    with ToSecurityGroupIdentifierOps
    with ToSecurityGroupOps
    with ToSecurityGroupReferenceOps
    with ToSendDiagnosticInterruptRequestOps
    with ToServiceConfigurationOps
    with ToServiceDetailOps
    with ToServiceTypeDetailOps
    with ToSlotDateTimeRangeRequestOps
    with ToSlotStartTimeRangeRequestOps
    with ToSnapshotDetailOps
    with ToSnapshotDiskContainerOps
    with ToSnapshotInfoOps
    with ToSnapshotOps
    with ToSnapshotTaskDetailOps
    with ToSpotDatafeedSubscriptionOps
    with ToSpotFleetLaunchSpecificationOps
    with ToSpotFleetMonitoringOps
    with ToSpotFleetRequestConfigDataOps
    with ToSpotFleetRequestConfigOps
    with ToSpotFleetTagSpecificationOps
    with ToSpotInstanceRequestOps
    with ToSpotInstanceStateFaultOps
    with ToSpotInstanceStatusOps
    with ToSpotMarketOptionsOps
    with ToSpotOptionsOps
    with ToSpotOptionsRequestOps
    with ToSpotPlacementOps
    with ToSpotPriceOps
    with ToStaleIpPermissionOps
    with ToStaleSecurityGroupOps
    with ToStartInstancesRequestOps
    with ToStartInstancesResponseOps
    with ToStartVpcEndpointServicePrivateDnsVerificationRequestOps
    with ToStartVpcEndpointServicePrivateDnsVerificationResponseOps
    with ToStateReasonOps
    with ToStopInstancesRequestOps
    with ToStopInstancesResponseOps
    with ToStorageLocationOps
    with ToStorageOps
    with ToSubnetAssociationOps
    with ToSubnetCidrBlockStateOps
    with ToSubnetIpv6CidrBlockAssociationOps
    with ToSubnetOps
    with ToSuccessfulInstanceCreditSpecificationItemOps
    with ToSuccessfulQueuedPurchaseDeletionOps
    with ToTagDescriptionOps
    with ToTagOps
    with ToTagSpecificationOps
    with ToTargetCapacitySpecificationOps
    with ToTargetCapacitySpecificationRequestOps
    with ToTargetConfigurationOps
    with ToTargetConfigurationRequestOps
    with ToTargetGroupOps
    with ToTargetGroupsConfigOps
    with ToTargetNetworkOps
    with ToTargetReservationValueOps
    with ToTerminateClientVpnConnectionsRequestOps
    with ToTerminateClientVpnConnectionsResponseOps
    with ToTerminateConnectionStatusOps
    with ToTerminateInstancesRequestOps
    with ToTerminateInstancesResponseOps
    with ToTrafficMirrorFilterOps
    with ToTrafficMirrorFilterRuleOps
    with ToTrafficMirrorPortRangeOps
    with ToTrafficMirrorPortRangeRequestOps
    with ToTrafficMirrorSessionOps
    with ToTrafficMirrorTargetOps
    with ToTransitGatewayAssociationOps
    with ToTransitGatewayAttachmentAssociationOps
    with ToTransitGatewayAttachmentOps
    with ToTransitGatewayAttachmentPropagationOps
    with ToTransitGatewayMulticastDeregisteredGroupMembersOps
    with ToTransitGatewayMulticastDeregisteredGroupSourcesOps
    with ToTransitGatewayMulticastDomainAssociationOps
    with ToTransitGatewayMulticastDomainAssociationsOps
    with ToTransitGatewayMulticastDomainOps
    with ToTransitGatewayMulticastGroupOps
    with ToTransitGatewayMulticastRegisteredGroupMembersOps
    with ToTransitGatewayMulticastRegisteredGroupSourcesOps
    with ToTransitGatewayOps
    with ToTransitGatewayOptionsOps
    with ToTransitGatewayPeeringAttachmentOps
    with ToTransitGatewayPropagationOps
    with ToTransitGatewayRequestOptionsOps
    with ToTransitGatewayRouteAttachmentOps
    with ToTransitGatewayRouteOps
    with ToTransitGatewayRouteTableAssociationOps
    with ToTransitGatewayRouteTableOps
    with ToTransitGatewayRouteTablePropagationOps
    with ToTransitGatewayVpcAttachmentOps
    with ToTransitGatewayVpcAttachmentOptionsOps
    with ToTunnelOptionOps
    with ToUnassignIpv6AddressesRequestOps
    with ToUnassignIpv6AddressesResponseOps
    with ToUnassignPrivateIpAddressesRequestOps
    with ToUnmonitorInstancesRequestOps
    with ToUnmonitorInstancesResponseOps
    with ToUnsuccessfulInstanceCreditSpecificationItemErrorOps
    with ToUnsuccessfulInstanceCreditSpecificationItemOps
    with ToUnsuccessfulItemErrorOps
    with ToUnsuccessfulItemOps
    with ToUpdateSecurityGroupRuleDescriptionsEgressRequestOps
    with ToUpdateSecurityGroupRuleDescriptionsEgressResponseOps
    with ToUpdateSecurityGroupRuleDescriptionsIngressRequestOps
    with ToUpdateSecurityGroupRuleDescriptionsIngressResponseOps
    with ToUserBucketDetailsOps
    with ToUserBucketOps
    with ToUserDataOps
    with ToUserIdGroupPairOps
    with ToVCpuInfoOps
    with ToVgwTelemetryOps
    with ToVolumeAttachmentOps
    with ToVolumeDetailOps
    with ToVolumeModificationOps
    with ToVolumeOps
    with ToVolumeStatusActionOps
    with ToVolumeStatusAttachmentStatusOps
    with ToVolumeStatusDetailsOps
    with ToVolumeStatusEventOps
    with ToVolumeStatusInfoOps
    with ToVolumeStatusItemOps
    with ToVpcAttachmentOps
    with ToVpcCidrBlockAssociationOps
    with ToVpcCidrBlockStateOps
    with ToVpcClassicLinkOps
    with ToVpcEndpointConnectionOps
    with ToVpcEndpointOps
    with ToVpcIpv6CidrBlockAssociationOps
    with ToVpcOps
    with ToVpcPeeringConnectionOps
    with ToVpcPeeringConnectionOptionsDescriptionOps
    with ToVpcPeeringConnectionStateReasonOps
    with ToVpcPeeringConnectionVpcInfoOps
    with ToVpnConnectionOps
    with ToVpnConnectionOptionsOps
    with ToVpnConnectionOptionsSpecificationOps
    with ToVpnGatewayOps
    with ToVpnStaticRouteOps
    with ToVpnTunnelOptionsSpecificationOps
    with ToWithdrawByoipCidrRequestOps
    with ToWithdrawByoipCidrResponseOps
