package com.github.j5ik2o.reactive.aws.cloudwatch.model.ops

import com.github.j5ik2o.reactive.aws.utils.ToOptionSupport

trait ToAllOps
    extends ToOptionSupport
    with ToAlarmHistoryItemOps
    with ToAnomalyDetectorConfigurationOps
    with ToAnomalyDetectorOps
    with ToCompositeAlarmOps
    with ToDashboardEntryOps
    with ToDashboardValidationMessageOps
    with ToDatapointOps
    with ToDeleteAlarmsRequestOps
    with ToDeleteAnomalyDetectorRequestOps
    with ToDeleteDashboardsRequestOps
    with ToDeleteInsightRulesRequestOps
    with ToDeleteInsightRulesResponseOps
    with ToDescribeAlarmHistoryRequestOps
    with ToDescribeAlarmHistoryResponseOps
    with ToDescribeAlarmsForMetricRequestOps
    with ToDescribeAlarmsForMetricResponseOps
    with ToDescribeAlarmsRequestOps
    with ToDescribeAlarmsResponseOps
    with ToDescribeAnomalyDetectorsRequestOps
    with ToDescribeAnomalyDetectorsResponseOps
    with ToDescribeInsightRulesRequestOps
    with ToDescribeInsightRulesResponseOps
    with ToDimensionFilterOps
    with ToDimensionOps
    with ToDisableAlarmActionsRequestOps
    with ToDisableInsightRulesRequestOps
    with ToDisableInsightRulesResponseOps
    with ToEnableAlarmActionsRequestOps
    with ToEnableInsightRulesRequestOps
    with ToEnableInsightRulesResponseOps
    with ToGetDashboardRequestOps
    with ToGetDashboardResponseOps
    with ToGetInsightRuleReportRequestOps
    with ToGetInsightRuleReportResponseOps
    with ToGetMetricDataRequestOps
    with ToGetMetricDataResponseOps
    with ToGetMetricStatisticsRequestOps
    with ToGetMetricStatisticsResponseOps
    with ToGetMetricWidgetImageRequestOps
    with ToGetMetricWidgetImageResponseOps
    with ToInsightRuleContributorDatapointOps
    with ToInsightRuleContributorOps
    with ToInsightRuleMetricDatapointOps
    with ToInsightRuleOps
    with ToListDashboardsRequestOps
    with ToListDashboardsResponseOps
    with ToListMetricsRequestOps
    with ToListMetricsResponseOps
    with ToListTagsForResourceRequestOps
    with ToListTagsForResourceResponseOps
    with ToMessageDataOps
    with ToMetricAlarmOps
    with ToMetricDataQueryOps
    with ToMetricDataResultOps
    with ToMetricDatumOps
    with ToMetricOps
    with ToMetricStatOps
    with ToPartialFailureOps
    with ToPutAnomalyDetectorRequestOps
    with ToPutCompositeAlarmRequestOps
    with ToPutDashboardRequestOps
    with ToPutDashboardResponseOps
    with ToPutInsightRuleRequestOps
    with ToPutMetricAlarmRequestOps
    with ToPutMetricDataRequestOps
    with ToRangeOps
    with ToSetAlarmStateRequestOps
    with ToStatisticSetOps
    with ToTagOps
    with ToTagResourceRequestOps
    with ToUntagResourceRequestOps
